### ISSUE TITLE
tkinter.TclError: no display name and no $DISPLAY environment variable

### ISSUE THREAD

**Issue by poyukao** [Kamnitsask/deepmedic#1]
I am running the deepmedic in a server and I ran into some troubles for plotting the training progress part. When I entered ''' python plotTrainingProgress.py -logs examples/output/logs/trainSessionWithValidTinyCnn.txt -class 0 ''', it gave me the error message:

Traceback (most recent call last):
  File "example.py", line 7, in <module>
    plt.scatter(x, y, s=20)
  File "/home/USER/.virtualenvs/nnet/lib/python2.7/site-packages/matplotlib/pyplot.py", line 3241, in scatter
    ax = gca()
  File "/home/USER/.virtualenvs/nnet/lib/python2.7/site-packages/matplotlib/pyplot.py", line 928, in gca
    return gcf().gca(**kwargs)
  File "/home/USER/.virtualenvs/nnet/lib/python2.7/site-packages/matplotlib/pyplot.py", line 578, in gcf
    return figure()
  File "/home/USER/.virtualenvs/nnet/lib/python2.7/site-packages/matplotlib/pyplot.py", line 527, in figure
**kwargs)
  File "/home/USER/.virtualenvs/nnet/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 84, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/home/USER/.virtualenvs/nnet/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 92, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/usr/local/lib/python2.7/lib-tk/Tkinter.py", line 1810, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

What is happening here?

I appreciate for your assistance.

**Comment by Kamnitsask** [comment]
Hello poyukao, 

First of all thanks a lot for your interest in my work and the feedback. Always appreciated :)

This is probably the classic error from matplotlib when you are logged on a remote machine (eg through ssh?) and try to display things. It cannot find the display device. 

Solutions:
Very nice solutions explained in: http://stackoverflow.com/questions/3453188/matplotlib-display-plot-on-a-remote-machine . In my case (local and remote machine run ubuntu), if I ssh to remote via "ssh -X remoteMachineName", fixes the error.

Please let me know if one of these solutions fixes your problem ;) Or if any new ones arise. Any feedback highly appreciated!

Note: This plotting script is not well put together. I will try to assign some time to update it.

Kostas

**Comment by poyukao** [comment]
Hello Kostas,

I appreciate your reply. The website and the solution you provided are very helpful. Finally, I ssh to remote via "ssh -X remoteMachineName" really fixed the error. I am able to get an beautiful plot now. 

Thank you again for your assitance. 

Best,
Po-Yu

**Comment by Kamnitsask** [comment]
Great, thanks a lot for letting me know. Hope you get some useful results out of it!

Issue closed.
