### ISSUE TITLE
Error when restarting model

### ISSUE THREAD

**Issue by andreimouraviev** [Kamnitsask/deepmedic#103]
I'm trying to continue training the model after my computer crashed but I keep getting this error.

Command: 
`./deepMedicRun -dev gpu7 -train ./somePath/modelConfig.cfg -model ./somePath/2018-03-20.19.11.08.751278.save`

Output:
```

Traceback (most recent call last):
  File "./deepMedicRun", line 134, in <module>
    deepMedicTrain.deepMedicTrainMain(absPathToTrainConf, absPathToCnnModelGivenInCmdLine, cnnInstanceLoaded, filenameAndPathWhereNewlyCreatedModelWasSaved, args.reset_optimizer)
  File "/home/amourav/deepmedic/deepmedic/frontEndModules/deepMedicTrain.py", line 323, in deepMedicTrainMain
    filepathToCnnModel = getAbsPathEvenIfRelativeIsGiven(configGet(trainConfig.CNN_MODEL_FILEPATH), trainConfigFilepath)
  File "/home/amourav/deepmedic/deepmedic/frontEndModules/frontEndHelpers/parsingFilesHelpers.py", line 12, in getAbsPathEvenIfRelativeIsGiven
    if os.path.isabs(pathGiven) :
  File "/home/amourav/anaconda2/lib/python2.7/posixpath.py", line 54, in isabs
    return s.startswith('/')
AttributeError: 'NoneType' object has no attribute 'startswith'

```

**Comment by Kamnitsask** [comment]
Hello,

This would mostly happen if path to the trainining-config does not exist (more likely). Have tiy double-checked the path that is being passed? Do you still get this error? Also note that in the above command, you use -train (correct) but point to a modelConfig.cfg file, while you need to point to a trainConfig.cfg.

Let me know if you ve solved this.

Kind regards,
Kostas
