### ISSUE TITLE
Index out of bounds error

### ISSUE THREAD

**Issue by charan223** [Kamnitsask/deepmedic#115]
Getting below error, when training on 4 classes (modified outputclasses value in modelconfig, didnt change anything else)

Trained on 0/100 of the batches for this subepoch...
Traceback (most recent call last):
  File "./deepMedicRun", line 186, in <module>
    deepMedicTrain.deepMedicTrainMain(absPathToTrainConf, absPathToCnnModelGivenInCmdLine, cnnInstanceLoaded, filenameAndPathWhereNewlyCreatedModelWasSaved, args.reset_optimizer)
  File "/home/charan/deepmedic/deepmedic/frontEndModules/deepMedicTrain.py", line 502, in deepMedicTrainMain
    do_training(*trainSessionParameters.getTupleForCnnTraining())
  File "/home/charan/deepmedic/deepmedic/routines/training.py", line 433, in do_training
    trainingAccuracyMonitorForEpoch)
  File "/home/charan/deepmedic/deepmedic/routines/training.py", line 51, in doTrainOrValidationOnBatchesAndReturnMeanAccuraciesOfSubepoch
    listWithCostMeanErrorAndRpRnTpTnForEachClassFromTraining = cnn3dInstance.cnnTrainModel(batch_i, vectorWithWeightsOfTheClassesForCostFunctionOfTraining)
  File "/home/charan/anaconda2/envs/deepm/lib/python2.7/site-packages/theano/compile/function_module.py", line 917, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/charan/anaconda2/envs/deepm/lib/python2.7/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/charan/anaconda2/envs/deepm/lib/python2.7/site-packages/theano/compile/function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
  File "/home/charan/anaconda2/envs/deepm/lib/python2.7/site-packages/theano/gof/op.py", line 892, in rval
    r = p(n, [x[0] for x in i], o)
  File "/home/charan/anaconda2/envs/deepm/lib/python2.7/site-packages/theano/tensor/subtensor.py", line 2322, in perform
    np.add.at(out[0], tuple(inputs[2:]), inputs[1])
IndexError: index 4 is out of bounds for axis 1 with size 4
Apply node that caused the error: AdvancedIncSubtensor{inplace=False,  set_instead_of_inc=False}(HostFromGpu(gpuarray).0, Assert{msg='`x[i]` and `y` do not have the same shape.'}.0, TensorConstant{[[[[0]]]

..
 [[[9]]]]}, HostFromGpu(gpuarray).0, TensorConstant{[[[[0]]

 ..
  [[8]]]]}, TensorConstant{[[[[0]
   ..
   [8]]]]}, TensorConstant{[[[[0 1 2 .. 6 7 8]]]]})
Toposort index: 1533
Inputs types: [TensorType(float32, 5D), TensorType(float32, (True, True, True, True)), TensorType(int64, (False, True, True, True)), TensorType(int32, 4D), TensorType(int64, (True, False, True, True)), TensorType(int64, (True, True, False, True)), TensorType(int64, (True, True, True, False))]
Inputs shapes: [(10, 4, 9, 9, 9), (1, 1, 1, 1), (10, 1, 1, 1), (10, 9, 9, 9), (1, 9, 1, 1), (1, 1, 9, 1), (1, 1, 1, 9)]
Inputs strides: [(11664, 2916, 324, 36, 4), (4, 4, 4, 4), (8, 8, 8, 8), (2916, 324, 36, 4), (72, 8, 8, 8), (72, 72, 8, 8), (72, 72, 72, 8)]
Inputs values: ['not shown', array([[[[-0.00013717]]]], dtype=float32), 'not shown', 'not shown', 'not shown', 'not shown', 'not shown']
Outputs clients: [[GpuFromHost<None>(AdvancedIncSubtensor{inplace=False,  set_instead_of_inc=False}.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "/home/charan/anaconda2/envs/deepm/lib/python2.7/site-packages/theano/gradient.py", line 1326, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/charan/anaconda2/envs/deepm/lib/python2.7/site-packages/theano/gradient.py", line 1021, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/charan/anaconda2/envs/deepm/lib/python2.7/site-packages/theano/gradient.py", line 1326, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/charan/anaconda2/envs/deepm/lib/python2.7/site-packages/theano/gradient.py", line 1021, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/charan/anaconda2/envs/deepm/lib/python2.7/site-packages/theano/gradient.py", line 1326, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/charan/anaconda2/envs/deepm/lib/python2.7/site-packages/theano/gradient.py", line 1021, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/charan/anaconda2/envs/deepm/lib/python2.7/site-packages/theano/gradient.py", line 1326, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/charan/anaconda2/envs/deepm/lib/python2.7/site-packages/theano/gradient.py", line 1162, in access_term_cache
    new_output_grads)
  File "/home/charan/anaconda2/envs/deepm/lib/python2.7/site-packages/theano/gradient.py", line 1326, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/charan/anaconda2/envs/deepm/lib/python2.7/site-packages/theano/gradient.py", line 1021, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/charan/anaconda2/envs/deepm/lib/python2.7/site-packages/theano/gradient.py", line 1326, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/charan/anaconda2/envs/deepm/lib/python2.7/site-packages/theano/gradient.py", line 1021, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/charan/anaconda2/envs/deepm/lib/python2.7/site-packages/theano/gradient.py", line 1326, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/charan/anaconda2/envs/deepm/lib/python2.7/site-packages/theano/gradient.py", line 1021, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/home/charan/anaconda2/envs/deepm/lib/python2.7/site-packages/theano/gradient.py", line 1326, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/home/charan/anaconda2/envs/deepm/lib/python2.7/site-packages/theano/gradient.py", line 1162, in access_term_cache
    new_output_grads)

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

**Comment by charan223** [comment]
No, I have 4 classes(including background)
