### ISSUE TITLE
Deepmedic Throws IndexError at training

### ISSUE THREAD

**Issue by ChenFeiL** [Kamnitsask/deepmedic#14]
Hi ,

I have been trying to work with the deepmedic package on the Brats2015 using gpu. The example with the full network runs absolutely fine. However, now I am trying our set of HGG and LGG cases with the same algorithm i.e. that is replacing the training and validation .cfg files with our cases. But the training phase throws an error  showing a problem with the index size. I'm sure the input images are all of the same dimensions. I'm copying the error below for your reference. I would appreciate your help on this.

-ChenFeiL

:=:=:=:=:=:=:=:=: Finished extracting Segments from the images for next Training. :=:=:=:=:=:=:=:=:
Loading Training data for subepoch #0 on shared variable...
TIMING: Loading sharedVariables for Training in epoch|subepoch=0|0 took time: 2.607758(s)
PARALLEL: Before Training in subepoch #0, submitting the parallel job for extracting Segments for the next Validation.
-T-T-T-T-T- Now Training for this subepoch... This may take a few minutes... -T-T-T-T-T-
Trained on 0/100 of the batches for this subepoch...
Traceback (most recent call last):
  File "./deepMedicRun", line 102, in<module>deepMedicTrain.deepMedicTrainMain(absPathToTrainConf, absPathToCnnModelGivenInCmdLine,cnnInstanceLoaded,filenameAndPathWhereNewlyCreatedModelWasSaved)
  File "/home/chenfei/deepmedic-master/deepmedic/frontEndModules/deepMedicTrain.py", line 440, in deepMedicTrainMain
    do_training(*trainSessionParameters.getTupleForCnnTraining())
  File "/home/chenfei/deepmedic-master/deepmedic/trainValidateTestVisualiseParallel.py", line 1500, in do_training
    subepoch)
  File "/home/chenfei/deepmedic-master/deepmedic/trainValidateTestVisualiseParallel.py", line 1029, in doTrainOrValidationOnBatchesAndReturnMeanAccuraciesOfSubepoch
    listWithCostMeanErrorAndRpRnTpTnForEachClassFromTraining = cnn3dInstance.cnnTrainModel(batch_i, vectorWithWeightsOfTheClassesForCostFunctionOfTraining)
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.8.2-py2.7.egg/theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.8.2-py2.7.egg/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.8.2-py2.7.egg/theano/compile/function_module.py", line 859, in __call__
    outputs = self.fn()
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.8.2-py2.7.egg/theano/gof/op.py", line 912, in rval
    r = p(n, [x[0] for x in i], o)
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.8.2-py2.7.egg/theano/tensor/subtensor.py", line 2166, in perform
    out[0] = inputs[0].__getitem__(inputs[1:])
IndexError: index 13 is out of bounds for axis 1 with size 5
Apply node that caused the error: AdvancedSubtensor(HostFromGpu.0, ARange{dtype='int64'}.0, Elemwise{Cast{int32}}.0)
Toposort index: 1890
Inputs types: [TensorType(float32, matrix), TensorType(int64, vector), TensorType(int32, vector)]
Inputs shapes: [(7290, 5), (7290,), (7290,)]
Inputs strides: [(20, 4), (8,), (4,)]
Inputs values: ['not shown', 'not shown', 'not shown']
Outputs clients: [[Sum{acc_dtype=float64}(AdvancedSubtensor.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "./deepMedicRun", line 95, in <module>
    (cnnInstanceLoaded, filenameAndPathWhereNewlyCreatedModelWasSaved) = deepMedicNewModel.deepMedicNewModelMain(absPathToModelConf)
  File "/home/chenfei/deepmedic-master/deepmedic/frontEndModules/deepMedicNewModel.py", line 192, in deepMedicNewModelMain
    cnn3dInstance.make_cnn_model(*createModelSessionParameters.getTupleForCnnCreation())
  File "/home/chenfei/deepmedic-master/deepmedic/cnn3d.py", line 1242, in make_cnn_model
    costFunctionLetter)
  File "/home/chenfei/deepmedic-master/deepmedic/cnn3d.py", line 602, in compileNewTrainFunction
    costFunctionFromLastLayer = self.fcLayers[-1].negativeLogLikelihood(y, weightsOfClassesInCostFunction)
  File "/home/chenfei/deepmedic-master/deepmedic/cnnLayerTypes.py", line 265, in negativeLogLikelihood
    return -T.mean( weighted_logOf_p_y_given_x[T.arange(y.shape[0]), y] )

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

**Comment by Kamnitsask** [comment]
Hello,

First of all, thanks a lot for your interest in my work. And sorry for the not very informative error messages... I should try to work on them, but this will take some work.

This error would usually be thrown when someone does not configure correctly the number of classes in the modelConfig.cfg (eg brats has 5, if you configure it to 2, this would be thrown). But I guess that's not the case, as the examples are preset correctly.

Would it be possible for you to email me the whole logs from the creation of the model (when you did the -newModel) and the train session?

Also, which version are you using? Either let me know the commit that you cloned from, or the version in the setup.py file.

Thanks,
Kostas

**Comment by ChenFeiL** [comment]
Hi Kamnitsask,

Thanks for your quick reply. I have solved the problem just now. I normalized the ground-truth labels to a zero-mean, unit-variance space mistakenly. After modifying the ground-truth labels, the training and testing models ran successfully. Thank you once again for your help.

-ChenFeiL

**Comment by Kamnitsask** [comment]
Wonderful, 

Feel free to keep me updated with how your attempts with using it go! Feedback is very very welcome at konstantinos.kamnitsas12@imperial.ac.uk.

And feel free to ask anything further you may need.

Kostas
