### ISSUE TITLE
when run the example, TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by linyangu1** [Kamnitsask/deepmedic#146]
Hi ,

I have been trying to work with the deepmedic package using gpu. The example with the full network failed when I run:  
             ./deepMedicRun -model ./examples/configFiles/deepMedic/model/modelConfig.cfg \
               -train ./examples/configFiles/deepMedic/train/trainConfig.cfg \
               -dev cuda0.

I would appreciate your help on this. Thanks a lot.

Below is the running log:
.......
************************************************************************************************
2019-01-24 17:50:37.769482 >> ************* Starting new Subepoch: #7/20 *************
2019-01-24 17:50:37.769482 >> ************************************************************************************************
2019-01-24 17:50:40.499487 >> PARALLEL: Before Validation in subepoch #7, the parallel job for extracting Segments for the next Training is submitted.
2019-01-24 17:50:40.546287 >> -V-V-V-V-V- Now Validating for this subepoch before commencing the training iterations... -V-V-V-V-V-
2019-01-24 17:50:40.546287 >> Validated on 0/104 of the batches for this subepoch...
2019-01-24 17:50:40.671088 >> :=:=:=:=:=:=:=:=: Starting to extract Segments from the images for next Training... :=:=:=:=:=:=:=:=:
2019-01-24 17:50:40.671088 >> Out of [2] subjects given for [Training], it was specified to extract Segments from maximum [50] per subepoch.
2019-01-24 17:50:40.671088 >> Shuffled indices of subjects that were randomly chosen: [1, 0]
2019-01-24 17:50:40.671088 >> SAMPLING: Starting iterations to extract Segments from each subject for next Training...
2019-01-24 17:50:40.671088 >> SAMPLING: Going to load the images and extract segments from the subject #1/2
2019-01-24 17:50:40.671088 >> Loading subject with 1st channel at: E:\deepmedic-master\examples\dataForExamples\brats2015TrainingData\train\brats_2013_pat0006_1\Flair_subtrMeanDivStd.nii.gz
2019-01-24 17:50:42.684491 >> WARN: GT labels were found of dtype=[float32]. Rounding and casting them to int!
2019-01-24 17:50:42.700091 >> Validated on 20/104 of the batches for this subepoch...
2019-01-24 17:50:43.012092 >> DEBUG: Index of this case in the original user-defined list of subjects: 1
2019-01-24 17:50:43.012092 >> Images for subject loaded.
2019-01-24 17:50:43.168092 >> From subject #0, sampling that many segments of Category [Foreground] : 250
2019-01-24 17:50:43.542493 >> Finished sampling segments of Category [Foreground]. Number sampled: 250
2019-01-24 17:50:43.573693 >> Validated on 40/104 of the batches for this subepoch...
2019-01-24 17:50:44.182094 >> From subject #0, sampling that many segments of Category [Background] : 250
2019-01-24 17:50:44.416094 >> Validated on 60/104 of the batches for this subepoch...
2019-01-24 17:50:44.556494 >> Finished sampling segments of Category [Background]. Number sampled: 250
2019-01-24 17:50:45.164896 >> SAMPLING: Going to load the images and extract segments from the subject #2/2
2019-01-24 17:50:45.164896 >> Loading subject with 1st channel at: E:\deepmedic-master\examples\dataForExamples\brats2015TrainingData\train\brats_2013_pat0005_1\Flair_subtrMeanDivStd.nii.gz
2019-01-24 17:50:45.383296 >> Validated on 80/104 of the batches for this subepoch...
2019-01-24 17:50:46.272497 >> Validated on 100/104 of the batches for this subepoch...
2019-01-24 17:50:46.428498 >> +++++++++++++++++++++++ Reporting Accuracy over whole subepoch +++++++++++++++++++++++
2019-01-24 17:50:46.444098 >> VALIDATION: Epoch #0, Subepoch #7, Overall:	 mean accuracy:   	0.9447	=> Correctly-Classified-Voxels/All-Predicted-Voxels = 4716/4992
2019-01-24 17:50:46.459698 >> +++++++++++++++ Reporting Accuracy over whole subepoch for Class-0 ++++++++ [Whole Foreground (Pos) Vs Background (Neg)] ++++++++++++++++
2019-01-24 17:50:46.459698 >> VALIDATION: Epoch #0, Subepoch #7, Class-0:	 mean accuracy:   	0.9778	=> (TruePos+TrueNeg)/All-Predicted-Voxels = 4881/4992
2019-01-24 17:50:46.459698 >> VALIDATION: Epoch #0, Subepoch #7, Class-0:	 mean sensitivity:	0.9650	=> TruePos/RealPos = 496/514
2019-01-24 17:50:46.459698 >> VALIDATION: Epoch #0, Subepoch #7, Class-0:	 mean specificity:	0.9792	=> TrueNeg/RealNeg = 4385/4478
2019-01-24 17:50:46.459698 >> VALIDATION: Epoch #0, Subepoch #7, Class-0:	 mean Dice:       	0.8994
2019-01-24 17:50:46.459698 >> +++++++++++++++ Reporting Accuracy over whole subepoch for Class-1 ++++++++ [This Class (Pos) Vs All Others (Neg)] ++++++++++++++++
2019-01-24 17:50:46.459698 >> VALIDATION: Epoch #0, Subepoch #7, Class-1:	 mean accuracy:   	0.9928	=> (TruePos+TrueNeg)/All-Predicted-Voxels = 4956/4992
2019-01-24 17:50:46.459698 >> VALIDATION: Epoch #0, Subepoch #7, Class-1:	 mean sensitivity:	0.7586	=> TruePos/RealPos = 22/29
2019-01-24 17:50:46.459698 >> VALIDATION: Epoch #0, Subepoch #7, Class-1:	 mean specificity:	0.9942	=> TrueNeg/RealNeg = 4934/4963
2019-01-24 17:50:46.459698 >> VALIDATION: Epoch #0, Subepoch #7, Class-1:	 mean Dice:       	0.5500
2019-01-24 17:50:46.459698 >> +++++++++++++++ Reporting Accuracy over whole subepoch for Class-2 ++++++++ [This Class (Pos) Vs All Others (Neg)] ++++++++++++++++
2019-01-24 17:50:46.459698 >> VALIDATION: Epoch #0, Subepoch #7, Class-2:	 mean accuracy:   	0.9517	=> (TruePos+TrueNeg)/All-Predicted-Voxels = 4751/4992
2019-01-24 17:50:46.459698 >> VALIDATION: Epoch #0, Subepoch #7, Class-2:	 mean sensitivity:	0.8285	=> TruePos/RealPos = 256/309
2019-01-24 17:50:46.459698 >> VALIDATION: Epoch #0, Subepoch #7, Class-2:	 mean specificity:	0.9599	=> TrueNeg/RealNeg = 4495/4683
2019-01-24 17:50:46.459698 >> VALIDATION: Epoch #0, Subepoch #7, Class-2:	 mean Dice:       	0.6799
2019-01-24 17:50:46.459698 >> +++++++++++++++ Reporting Accuracy over whole subepoch for Class-3 ++++++++ [This Class (Pos) Vs All Others (Neg)] ++++++++++++++++
2019-01-24 17:50:46.459698 >> VALIDATION: Epoch #0, Subepoch #7, Class-3:	 mean accuracy:   	0.9776	=> (TruePos+TrueNeg)/All-Predicted-Voxels = 4880/4992
2019-01-24 17:50:46.459698 >> VALIDATION: Epoch #0, Subepoch #7, Class-3:	 mean sensitivity:	0.0093	=> TruePos/RealPos = 1/107
2019-01-24 17:50:46.475298 >> VALIDATION: Epoch #0, Subepoch #7, Class-3:	 mean specificity:	0.9988	=> TrueNeg/RealNeg = 4879/4885
2019-01-24 17:50:46.475298 >> VALIDATION: Epoch #0, Subepoch #7, Class-3:	 mean Dice:       	0.0175
2019-01-24 17:50:46.475298 >> +++++++++++++++ Reporting Accuracy over whole subepoch for Class-4 ++++++++ [This Class (Pos) Vs All Others (Neg)] ++++++++++++++++
2019-01-24 17:50:46.475298 >> VALIDATION: Epoch #0, Subepoch #7, Class-4:	 mean accuracy:   	0.9896	=> (TruePos+TrueNeg)/All-Predicted-Voxels = 4940/4992
2019-01-24 17:50:46.475298 >> VALIDATION: Epoch #0, Subepoch #7, Class-4:	 mean sensitivity:	0.7536	=> TruePos/RealPos = 52/69
2019-01-24 17:50:46.475298 >> VALIDATION: Epoch #0, Subepoch #7, Class-4:	 mean specificity:	0.9929	=> TrueNeg/RealNeg = 4888/4923
2019-01-24 17:50:46.475298 >> VALIDATION: Epoch #0, Subepoch #7, Class-4:	 mean Dice:       	0.6667
2019-01-24 17:50:46.475298 >> TIMING: Validating on the batches of this subepoch #7 took time: 5.929010629653931(s)
2019-01-24 17:50:46.771698 >> WARN: GT labels were found of dtype=[float32]. Rounding and casting them to int!
2019-01-24 17:50:47.005699 >> DEBUG: Index of this case in the original user-defined list of subjects: 0
2019-01-24 17:50:47.005699 >> Images for subject loaded.
2019-01-24 17:50:47.146099 >> From subject #1, sampling that many segments of Category [Foreground] : 250
2019-01-24 17:50:47.442500 >> Finished sampling segments of Category [Foreground]. Number sampled: 250
2019-01-24 17:50:47.941700 >> From subject #1, sampling that many segments of Category [Background] : 250
2019-01-24 17:50:48.238101 >> Finished sampling segments of Category [Background]. Number sampled: 250
2019-01-24 17:50:48.799702 >> TIMING: Extracting all the Segments for next Training took time: 8.133740797261453(s)
2019-01-24 17:50:48.799702 >> :=:=:=:=:=:=:=:=: Finished extracting Segments from the images for next Training. :=:=:=:=:=:=:=:=:
2019-01-24 17:51:02.731526 >> PARALLEL: Before Training in subepoch #7, submitting the parallel job for extracting Segments for the next Validation.
2019-01-24 17:51:02.949927 >> -T-T-T-T-T- Now Training for this subepoch... This may take a few minutes... -T-T-T-T-T-
2019-01-24 17:51:02.965527 >> Trained on 0/100 of the batches for this subepoch...
2019-01-24 17:51:03.137127 >> :=:=:=:=:=:=:=:=: Starting to extract Segments from the images for next Validation... :=:=:=:=:=:=:=:=:
2019-01-24 17:51:03.168327 >> Out of [2] subjects given for [Validation], it was specified to extract Segments from maximum [50] per subepoch.
2019-01-24 17:51:03.199527 >> Shuffled indices of subjects that were randomly chosen: [0, 1]
2019-01-24 17:51:03.199527 >> SAMPLING: Starting iterations to extract Segments from each subject for next Validation...
2019-01-24 17:51:03.215127 >> SAMPLING: Going to load the images and extract segments from the subject #1/2
2019-01-24 17:51:03.215127 >> Loading subject with 1st channel at: E:\deepmedic-master\examples\dataForExamples\brats2015TrainingData\validation\brats_2013_pat0003_1\Flair_subtrMeanDivStd.nii.gz
2019-01-24 17:51:05.633132 >> WARN: GT labels were found of dtype=[float32]. Rounding and casting them to int!
2019-01-24 17:51:05.913932 >> DEBUG: Index of this case in the original user-defined list of subjects: 0
2019-01-24 17:51:05.945132 >> Images for subject loaded.
2019-01-24 17:51:05.960732 >> From subject #0, sampling that many segments of Category [Uniform] : 2500
2019-01-24 17:51:06.335133 >> Finished sampling segments of Category [Uniform]. Number sampled: 2500
2019-01-24 17:51:08.347536 >> SAMPLING: Going to load the images and extract segments from the subject #2/2
2019-01-24 17:51:08.347536 >> Loading subject with 1st channel at: E:\deepmedic-master\examples\dataForExamples\brats2015TrainingData\validation\brats_2013_pat0004_1\Flair_subtrMeanDivStd.nii.gz
2019-01-24 17:51:10.094739 >> WARN: GT labels were found of dtype=[float32]. Rounding and casting them to int!
2019-01-24 17:51:10.391140 >> DEBUG: Index of this case in the original user-defined list of subjects: 1
2019-01-24 17:51:10.391140 >> Images for subject loaded.
2019-01-24 17:51:10.437940 >> From subject #1, sampling that many segments of Category [Uniform] : 2500
2019-01-24 17:51:10.874741 >> Finished sampling segments of Category [Uniform]. Number sampled: 2500
2019-01-24 17:51:15.507949 >> TIMING: Extracting all the Segments for next Validation took time: 12.38895934405491(s)
2019-01-24 17:51:15.507949 >> :=:=:=:=:=:=:=:=: Finished extracting Segments from the images for next Validation. :=:=:=:=:=:=:=:=:
2019-01-24 17:52:04.308835 >> Trained on 20/100 of the batches for this subepoch...
2019-01-24 17:53:01.849736 >> Trained on 40/100 of the batches for this subepoch...
2019-01-24 17:53:55.955032 >> Trained on 60/100 of the batches for this subepoch...
2019-01-24 17:54:50.287730 >> Trained on 80/100 of the batches for this subepoch...
2019-01-24 17:55:43.850624 >> +++++++++++++++++++++++ Reporting Accuracy over whole subepoch +++++++++++++++++++++++
2019-01-24 17:55:43.850624 >> TRAINING: Epoch #0, Subepoch #7, Overall:	 mean accuracy:   	0.9216	=> Correctly-Classified-Voxels/All-Predicted-Voxels = 8535146/9261000
2019-01-24 17:55:43.850624 >> TRAINING: Epoch #0, Subepoch #7, Overall:	 mean cost:      	0.56227
2019-01-24 17:55:43.850624 >> +++++++++++++++ Reporting Accuracy over whole subepoch for Class-0 ++++++++ [Whole Foreground (Pos) Vs Background (Neg)] ++++++++++++++++
2019-01-24 17:55:43.850624 >> TRAINING: Epoch #0, Subepoch #7, Class-0:	 mean accuracy:   	0.9604	=> (TruePos+TrueNeg)/All-Predicted-Voxels = 8893826/9261000
2019-01-24 17:55:43.850624 >> TRAINING: Epoch #0, Subepoch #7, Class-0:	 mean sensitivity:	0.9348	=> TruePos/RealPos = 3095874/3311644
2019-01-24 17:55:43.850624 >> TRAINING: Epoch #0, Subepoch #7, Class-0:	 mean specificity:	0.9746	=> TrueNeg/RealNeg = 5797952/5949356
2019-01-24 17:55:43.850624 >> TRAINING: Epoch #0, Subepoch #7, Class-0:	 mean Dice:       	0.9440
2019-01-24 17:55:43.850624 >> +++++++++++++++ Reporting Accuracy over whole subepoch for Class-1 ++++++++ [This Class (Pos) Vs All Others (Neg)] ++++++++++++++++
2019-01-24 17:55:43.850624 >> TRAINING: Epoch #0, Subepoch #7, Class-1:	 mean accuracy:   	0.9794	=> (TruePos+TrueNeg)/All-Predicted-Voxels = 9070094/9261000
2019-01-24 17:55:43.850624 >> TRAINING: Epoch #0, Subepoch #7, Class-1:	 mean sensitivity:	0.9041	=> TruePos/RealPos = 830636/918761
2019-01-24 17:55:43.850624 >> TRAINING: Epoch #0, Subepoch #7, Class-1:	 mean specificity:	0.9877	=> TrueNeg/RealNeg = 8239458/8342239
2019-01-24 17:55:43.850624 >> TRAINING: Epoch #0, Subepoch #7, Class-1:	 mean Dice:       	0.8969
2019-01-24 17:55:43.850624 >> +++++++++++++++ Reporting Accuracy over whole subepoch for Class-2 ++++++++ [This Class (Pos) Vs All Others (Neg)] ++++++++++++++++
2019-01-24 17:55:43.850624 >> TRAINING: Epoch #0, Subepoch #7, Class-2:	 mean accuracy:   	0.9508	=> (TruePos+TrueNeg)/All-Predicted-Voxels = 8805689/9261000
2019-01-24 17:55:43.850624 >> TRAINING: Epoch #0, Subepoch #7, Class-2:	 mean sensitivity:	0.8255	=> TruePos/RealPos = 1124837/1362617
2019-01-24 17:55:43.850624 >> TRAINING: Epoch #0, Subepoch #7, Class-2:	 mean specificity:	0.9725	=> TrueNeg/RealNeg = 7680852/7898383
2019-01-24 17:55:43.850624 >> TRAINING: Epoch #0, Subepoch #7, Class-2:	 mean Dice:       	0.8317
2019-01-24 17:55:43.850624 >> +++++++++++++++ Reporting Accuracy over whole subepoch for Class-3 ++++++++ [This Class (Pos) Vs All Others (Neg)] ++++++++++++++++
2019-01-24 17:55:43.850624 >> TRAINING: Epoch #0, Subepoch #7, Class-3:	 mean accuracy:   	0.9779	=> (TruePos+TrueNeg)/All-Predicted-Voxels = 9056226/9261000
2019-01-24 17:55:43.850624 >> TRAINING: Epoch #0, Subepoch #7, Class-3:	 mean sensitivity:	0.4626	=> TruePos/RealPos = 120988/261544
2019-01-24 17:55:43.850624 >> TRAINING: Epoch #0, Subepoch #7, Class-3:	 mean specificity:	0.9929	=> TrueNeg/RealNeg = 8935238/8999456
2019-01-24 17:55:43.850624 >> TRAINING: Epoch #0, Subepoch #7, Class-3:	 mean Dice:       	0.5416
2019-01-24 17:55:43.850624 >> +++++++++++++++ Reporting Accuracy over whole subepoch for Class-4 ++++++++ [This Class (Pos) Vs All Others (Neg)] ++++++++++++++++
2019-01-24 17:55:43.850624 >> TRAINING: Epoch #0, Subepoch #7, Class-4:	 mean accuracy:   	0.9748	=> (TruePos+TrueNeg)/All-Predicted-Voxels = 9027457/9261000
2019-01-24 17:55:43.850624 >> TRAINING: Epoch #0, Subepoch #7, Class-4:	 mean sensitivity:	0.8595	=> TruePos/RealPos = 660733/768722
2019-01-24 17:55:43.850624 >> TRAINING: Epoch #0, Subepoch #7, Class-4:	 mean specificity:	0.9852	=> TrueNeg/RealNeg = 8366724/8492278
2019-01-24 17:55:43.850624 >> TRAINING: Epoch #0, Subepoch #7, Class-4:	 mean Dice:       	0.8498
2019-01-24 17:55:43.866224 >> TIMING: Training on the batches of this subepoch #7 took time: 280.9162971973419(s)
2019-01-24 17:55:43.866224 >> **************************************************************************************************
2019-01-24 17:55:43.866224 >> ************* Starting new Subepoch: #8/20 *************
2019-01-24 17:55:43.866224 >> **************************************************************************************************
2019-01-24 17:55:44.240625 >> 
2019-01-24 17:55:44.240625 >> ERROR: Caught exception from main process: 'NoneType' object is not iterable
2019-01-24 17:55:45.426227 >> Traceback (most recent call last):
  File "E:/deepmedic-master/deepMedicRun", line 179, in <module>
    session.run_session(sess_device, model_params, args.reset_trainer)
  File "E:\deepmedic-master\deepmedic\frontEnd\trainSession.py", line 160, in run_session
    do_training( *( [sessionTf, saver_all, cnn3d, trainer] + self._params.get_args_for_train_routine() ) )
  File "E:\deepmedic-master\deepmedic\routines\training.py", line 297, in do_training
    labelsForCentralOfSegmentsForSubepVal] = parallelJobToGetDataForNextValidation() #fromParallelProcessing that had started from last loop when it was submitted.
TypeError: 'NoneType' object is not iterable

2019-01-24 17:56:01.119854 >> Finished.

Linyan

**Comment by linyangu1** [comment]
Hi Kamnitask.

Thank you for your reply.

I did it more than once, and the same error occurred. 

The versions of the libraries I am using are:

- python: 3.5
- tensorflow-gpu: 1.3.0
- numpy: 1.16.0
- pp: 1.6.4
- nibabel: 2.3.3

I checked my standard-output (terminal) and found "MemoryError". I tried downgrading the versions of
nibabel to 2.2.1, but the same error occurred. 

Below is the detailed  standard-output:

:=:=:=:=:=:=:=:=: Finished extracting Segments from the images for next Validation. :=:=:=:=:=:=:=:=:
A fatal error has occured during the function execution
Traceback (most recent call last):
  File "C:\Users\siat\AppData\Local\Programs\Python\Python35\lib\site-packages\ppworker.py", line 114, in run
    self.pickle_proto)
MemoryError
 
ERROR: Caught exception from main process: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "E:/deepmedic-master/deepMedicRun", line 179, in <module>
    session.run_session(sess_device, model_params, args.reset_trainer)
  File "E:\deepmedic-master\deepmedic\frontEnd\trainSession.py", line 160, in run_session
    do_training( *( [sessionTf, saver_all, cnn3d, trainer] + self._params.get_args_for_train_routine() ) )
  File "E:\deepmedic-master\deepmedic\routines\training.py", line 297, in do_training
    labelsForCentralOfSegmentsForSubepVal] = parallelJobToGetDataForNextValidation() #fromParallelProcessing that had started from last loop when it was submitted.
TypeError: 'NoneType' object is not iterable

Finished.
=========================================================

Regards,
Linyan

**Comment by Kamnitsask** [comment]
Thanks for the update.

Then yes, sound like it's the same Memory issue with issue #145 that I recently raised, which happens with the recent versions.

A temporary workaround would be to simply create a virtualenvirnoment with the downgraded stable versions I have noted there #145.

This issue is not of high priority to be fixed. Problem is I will not make time for it in the next 2 weeks as I am overwhelmed with teaching, but will be the first thing I look into then.

Sorry, but it may not be a DM problem but a dependency's issue. Just work with a downgraded virtual env for a while.

virtualenv -p python2 ve_dm_py2
source ve_dm_py2/bin/activate
pip install numpy==1.14.3
pip install nibabel==2.2.1
pip install pp==1.6.5
pip install tensorflow==1.8.0

thanks,
k

**Comment by linyangu1** [comment]
Thank you very much for your kindness, this problem has been solved.

**Comment by linyangu1** [comment]
Thank you very much for your kindness. The question has been solved.

**Comment by linyangu1** [comment]
Thank you very much for your kindness. The problem has been solved.

**Comment by linyangu1** [comment]
Hi Kamnitask.

Thank you for your reply.

I worked with a downgraded virtual env and the versions of the libraries are:

-python==3.5
- numpy==1.14.3
- nibabel==2.2.1
- pp==1.6.4.4 (for python 3)
- tensorflow==1.8.0

The MemoryError seemed to be fixed, and the training phase run 3 epoch until an error occurred. However, another error occurred.

(when I run:
./deepMedicRun -model ./examples/configFiles/deepMedic/model/modelConfig.cfg 
-train ./examples/configFiles/deepMedic/train/trainConfig.cfg 
-dev cuda0.)

Below is the detailed standard-output:


+++++++++++++++ Reporting Accuracy over whole subepoch for Class-3 ++++++++ [This Class (Pos) Vs All Others (Neg)] ++++++++++++++++
TRAINING: Epoch #3, Subepoch #10, Class-3:	 mean accuracy:   	0.9827	=> (TruePos+TrueNeg)/All-Predicted-Voxels = 9100509/9261000
TRAINING: Epoch #3, Subepoch #10, Class-3:	 mean sensitivity:	0.6852	=> TruePos/RealPos = 207824/303303
TRAINING: Epoch #3, Subepoch #10, Class-3:	 mean specificity:	0.9927	=> TrueNeg/RealNeg = 8892685/8957697
TRAINING: Epoch #3, Subepoch #10, Class-3:	 mean Dice:       	0.7214
+++++++++++++++ Reporting Accuracy over whole subepoch for Class-4 ++++++++ [This Class (Pos) Vs All Others (Neg)] ++++++++++++++++
TRAINING: Epoch #3, Subepoch #10, Class-4:	 mean accuracy:   	0.9829	=> (TruePos+TrueNeg)/All-Predicted-Voxels = 9102577/9261000
TRAINING: Epoch #3, Subepoch #10, Class-4:	 mean sensitivity:	0.9107	=> TruePos/RealPos = 707200/776552
TRAINING: Epoch #3, Subepoch #10, Class-4:	 mean specificity:	0.9895	=> TrueNeg/RealNeg = 8395377/8484448
TRAINING: Epoch #3, Subepoch #10, Class-4:	 mean Dice:       	0.8993
TIMING: Training on the batches of this subepoch #10 took time: 197.8643171787262(s)
**************************************************************************************************
************* Starting new Subepoch: #11/20 *************
**************************************************************************************************

ERROR: Caught exception from main process: 'utf-8' codec can't decode byte 0xbf in position 256410: invalid start byte
Traceback (most recent call last):
  File "E:/deepmedic-master/deepMedicRun", line 179, in <module>
    session.run_session(sess_device, model_params, args.reset_trainer)
  File "E:\deepmedic-master\deepmedic\frontEnd\trainSession.py", line 160, in run_session
    do_training( *( [sessionTf, saver_all, cnn3d, trainer] + self._params.get_args_for_train_routine() ) )
  File "E:\deepmedic-master\deepmedic\routines\training.py", line 297, in do_training
    labelsForCentralOfSegmentsForSubepVal] = parallelJobToGetDataForNextValidation() #fromParallelProcessing that had started from last loop when it was submitted.
  File "E:\Python Program\myproject3.5\env\lib\site-packages\pp.py", line 126, in __call__
    self.__unpickle()
  File "E:\Python Program\myproject3.5\env\lib\site-packages\pp.py", line 141, in __unpickle
    self.result, sout = pickle.loads(ppc.b_(self.sresult))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 256410: invalid start byte
========================================================================

Regards,
Linyan

**Comment by linyangu1** [comment]
Hi Kamnitask.

Thank you for your reply.

I worked with a downgraded virtual env and the versions of the libraries are:

-python==3.5

numpy==1.14.3
nibabel==2.2.1
pp==1.6.4.4 (for python 3)
tensorflow==1.8.0
The MemoryError seemed to be fixed, and the training phase run 3 epoch until an error occurred. However, another error occurred.

(when I run:
./deepMedicRun -model ./examples/configFiles/deepMedic/model/modelConfig.cfg
-train ./examples/configFiles/deepMedic/train/trainConfig.cfg
-dev cuda0.)

Below is the detailed standard-output:

+++++++++++++++ Reporting Accuracy over whole subepoch for Class-3 ++++++++ [This Class (Pos) Vs All Others (Neg)] ++++++++++++++++
TRAINING: Epoch #3, Subepoch #10, Class-3:	mean accuracy: 0.9827	=> (TruePos+TrueNeg)/All-Predicted-Voxels = 9100509/9261000
TRAINING: Epoch #3, Subepoch #10, Class-3:	mean sensitivity:	0.6852	=> TruePos/RealPos = 207824/303303
TRAINING: Epoch #3, Subepoch #10, Class-3:	mean specificity:	0.9927	=> TrueNeg/RealNeg = 8892685/8957697
TRAINING: Epoch #3, Subepoch #10, Class-3:	mean Dice: 0.7214
+++++++++++++++ Reporting Accuracy over whole subepoch for Class-4 ++++++++ [This Class (Pos) Vs All Others (Neg)] ++++++++++++++++
TRAINING: Epoch #3, Subepoch #10, Class-4:	mean accuracy: 0.9829	=> (TruePos+TrueNeg)/All-Predicted-Voxels = 9102577/9261000
TRAINING: Epoch #3, Subepoch #10, Class-4:	mean sensitivity:	0.9107	=> TruePos/RealPos = 707200/776552
TRAINING: Epoch #3, Subepoch #10, Class-4:	mean specificity:	0.9895	=> TrueNeg/RealNeg = 8395377/8484448
TRAINING: Epoch #3, Subepoch #10, Class-4:	mean Dice: 0.8993
TIMING: Training on the batches of this subepoch #10 took time: 197.8643171787262(s)

************* Starting new Subepoch: #11/20 *************

ERROR: Caught exception from main process: 'utf-8' codec can't decode byte 0xbf in position 256410: invalid start byte
Traceback (most recent call last):
File "E:/deepmedic-master/deepMedicRun", line 179, in 
session.run_session(sess_device, model_params, args.reset_trainer)
File "E:\deepmedic-master\deepmedic\frontEnd\trainSession.py", line 160, in run_session
do_training( *( [sessionTf, saver_all, cnn3d, trainer] + self._params.get_args_for_train_routine() ) )
File "E:\deepmedic-master\deepmedic\routines\training.py", line 297, in do_training
labelsForCentralOfSegmentsForSubepVal] = parallelJobToGetDataForNextValidation() #fromParallelProcessing that had started from last loop when it was submitted.
File "E:\Python Program\myproject3.5\env\lib\site-packages\pp.py", line 126, in call
self.__unpickle()
File "E:\Python Program\myproject3.5\env\lib\site-packages\pp.py", line 141, in _unpickle
self.result, sout = pickle.loads(ppc.b(self.sresult))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 256410: invalid start byte

Regards,
Linyan

**Comment by linyangu1** [comment]
Hi Kamnitask.

Thank you for your reply.

I worked with a downgraded virtual env and the versions of the libraries are:

-python==3.5

numpy==1.14.3
nibabel==2.2.1
pp==1.6.4.4 (for python 3)
tensorflow==1.8.0
The MemoryError seemed to be fixed, and the training phase run 3 epoch until an error occurred. However, another error occurred.

(when I run:
./deepMedicRun -model ./examples/configFiles/deepMedic/model/modelConfig.cfg
-train ./examples/configFiles/deepMedic/train/trainConfig.cfg
-dev cuda0.)

Below is the detailed standard-output:

+++++++++++++++ Reporting Accuracy over whole subepoch for Class-3 ++++++++ [This Class (Pos) Vs All Others (Neg)] ++++++++++++++++
TRAINING: Epoch #3, Subepoch #10, Class-3:	mean accuracy: 0.9827	=> (TruePos+TrueNeg)/All-Predicted-Voxels = 9100509/9261000
TRAINING: Epoch #3, Subepoch #10, Class-3:	mean sensitivity:	0.6852	=> TruePos/RealPos = 207824/303303
TRAINING: Epoch #3, Subepoch #10, Class-3:	mean specificity:	0.9927	=> TrueNeg/RealNeg = 8892685/8957697
TRAINING: Epoch #3, Subepoch #10, Class-3:	mean Dice: 0.7214
+++++++++++++++ Reporting Accuracy over whole subepoch for Class-4 ++++++++ [This Class (Pos) Vs All Others (Neg)] ++++++++++++++++
TRAINING: Epoch #3, Subepoch #10, Class-4:	mean accuracy: 0.9829	=> (TruePos+TrueNeg)/All-Predicted-Voxels = 9102577/9261000
TRAINING: Epoch #3, Subepoch #10, Class-4:	mean sensitivity:	0.9107	=> TruePos/RealPos = 707200/776552
TRAINING: Epoch #3, Subepoch #10, Class-4:	mean specificity:	0.9895	=> TrueNeg/RealNeg = 8395377/8484448
TRAINING: Epoch #3, Subepoch #10, Class-4:	mean Dice: 0.8993
TIMING: Training on the batches of this subepoch #10 took time: 197.8643171787262(s)

************* Starting new Subepoch: #11/20 *************

ERROR: Caught exception from main process: 'utf-8' codec can't decode byte 0xbf in position 256410: invalid start byte
Traceback (most recent call last):
File "E:/deepmedic-master/deepMedicRun", line 179, in 
session.run_session(sess_device, model_params, args.reset_trainer)
File "E:\deepmedic-master\deepmedic\frontEnd\trainSession.py", line 160, in run_session
do_training( *( [sessionTf, saver_all, cnn3d, trainer] + self._params.get_args_for_train_routine() ) )
File "E:\deepmedic-master\deepmedic\routines\training.py", line 297, in do_training
labelsForCentralOfSegmentsForSubepVal] = parallelJobToGetDataForNextValidation() #fromParallelProcessing that had started from last loop when it was submitted.
File "E:\Python Program\myproject3.5\env\lib\site-packages\pp.py", line 126, in call
self.__unpickle()
File "E:\Python Program\myproject3.5\env\lib\site-packages\pp.py", line 141, in _unpickle
self.result, sout = pickle.loads(ppc.b(self.sresult))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 256410: invalid start byte

Regards,
Linyan

**Comment by Kamnitsask** [comment]
Hi Linyan,
(sorry for late reply. I was overwhelmed with some teaching stuff)

I have not seen this problem before. This looks as if the process failed at loading something from disk (pickle.load). Did it happen more than once? 
Did you retry and got this problem more than once?

It looks as if this is coming from pp (unpickling something for itself).

I today started looking into finding which library has memory problems from the above, and I will then try taking pp out and switching to another library.

If you would like to try something in the mean time is to disable pp, and see if this stops happening (and then we will know it's pp):
- Go to ./deepmedic/routines/training.py
- Line 266: Change "if boolItIsTheVeryFirstSubepochOfThisProcess :" to "if True:"
- Put in comment Lines 306-to-309 (the job_server.submit(), so that it wont happen).
- Line 332: Change "if (not ...) and ... : " to "if True:"
- Put in comments the Lines 370-to-382 (the calls of job_server.submit() again).

Sorry for the troubles, let me know if you notice something new.

K

**Comment by Kamnitsask** [comment]
If you would like, try the latest version, v0.7.1, where the pp module has been replaced with multiprocessing, for which version I have not seen memory problems. (perhaps you will want to build a new virtualenv with python 3 and latest version of libraries).

The version comes with a bit better exception handling as well, so it may help more to find what problems you have.

K

**Comment by linyangu1** [comment]
Hi Kamnitask，

Sorry for late reply.

I tried the latest version. And it works now. 

Thank you for your help.

Linyan

**Comment by Kamnitsask** [comment]
Excellent, thanks, good to know this is solved.

Sorry for the trouble. Ensuring compatibility with each new library version is not as easy as it may seem.
