### ISSUE TITLE
Testing on the gpu fails:

### ISSUE THREAD

**Issue by josephwinston** [Kamnitsask/deepmedic#16]
I'm on eba26d7 and when I test the model following the example in ```README.md```, the following error is displayed:

```python
Traceback (most recent call last):
  File "deepMedicRun", line 109, in <module>
    deepMedicTest.deepMedicTestMain(absPathToTestConf, absPathToCnnModelGivenInCmdLine)
  File "D:\home\josephwinston\src\Remote\GIT\deepmedic\deepmedic\frontEndModules\deepMedicTest.py", line 265, in deepMedicTestMain
    listOfAListPerChannelWithFilepathsOfAllCases = [parseAbsFileLinesInList(getAbsPathEvenIfRelativeIsGiven(channelConfPath, testConfigFilepath)) for channelConfPath in configGet(testConfig.CHANNELS)]

TypeError: 'NoneType' object is not iterable
```
Invocation that I am using and the output from the run is:

```python
(theano) $ python deepMedicRun -test examples/configFiles/tinyCnn/train/trainConfigWithValidation.cfg -model "examples/output/cnnModels/trainSessionWithVal
idTinyCnn/tinyCnn.trainSessionWithValidTinyCnn.final.2016-08-31 08.07.18.906000.save"
Given Test-Configuration File:  D:\home\josephwinston\src\Remote\GIT\deepmedic\examples\configFiles\tinyCnn\train\trainConfigWithValidation.cfg
>>Creating necessary folders for testing-session...
CONFIG: The configuration file for the testing session was loaded from: D:\home\josephwinston\src\Remote\GIT\deepmedic\examples\configFiles\tinyCnn\train\trainConfigWithValidation.cfg
=========== Loading the CNN model for testing... ===============
WARN: A CNN-Model to use was specified both in the command line input and in the test-config-file! The input by the command line will be used: D:\home\josephwinston\src\Remote\GIT\deepmedic\examples\o
utput\cnnModels\trainSessionWithValidTinyCnn\tinyCnn.trainSessionWithValidTinyCnn.final.2016-08-31 08.07.18.906000.save
...Loading the network can take a few minutes if the model is big...
DEBUG: nvcc STDOUT mod.cu
   Creating library C:/Users/hb55683/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-2.7.12-64/tmpdyp3uv/265abc51f7c376c224983485238ff1a5.lib a
nd object C:/Users/hb55683/AppData/Local/Theano/compiledir_Windows-7-6.1.7601-SP1-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-2.7.12-64/tmpdyp3uv/265abc51f7c376c224983485238ff1a5.exp

Using gpu device 0: Quadro K5100M (CNMeM is enabled with initial size: 95.0% of memory, cuDNN 5005)
The CNN model was loaded successfully from: D:\home\josephwinston\src\Remote\GIT\deepmedic\examples\output\cnnModels\trainSessionWithValidTinyCnn\tinyCnn.trainSessionWithValidTinyCnn.final.2016-08-31
08.07.18.906000.save
Traceback (most recent call last):
  File "deepMedicRun", line 109, in <module>
    deepMedicTest.deepMedicTestMain(absPathToTestConf, absPathToCnnModelGivenInCmdLine)
  File "D:\home\josephwinston\src\Remote\GIT\deepmedic\deepmedic\frontEndModules\deepMedicTest.py", line 265, in deepMedicTestMain
    listOfAListPerChannelWithFilepathsOfAllCases = [parseAbsFileLinesInList(getAbsPathEvenIfRelativeIsGiven(channelConfPath, testConfigFilepath)) for channelConfPath in configGet(testConfig.CHANNELS)]

TypeError: 'NoneType' object is not iterable
```

**Comment by Kamnitsask** [comment]
Hello Joseph,

"python deepMedicRun -test examples/configFiles/tinyCnn/train/trainConfigWithValidation.cfg"
It seems you pointed to the "training config" when trying to test. You should point to the corresponding testing one. ie, at tinyCnn/test/testConfig.cfg.

Let me know if everything goes fine after that.

Many many thanks for the feedback Joseph. And I am sorry for the little informative error messages. It will require some time until I improve over the checks and errors thrown...

Kostas

**Comment by josephwinston** [comment]
Thank you for providing another set of eyes.  Everything is working now.  Please close.

**Comment by Kamnitsask** [comment]
Keep the feedback coming Joseph. It's far from a modular/robust piece of code, but I m always glad to know of users' issues, hoping to make it a bit more useful + less frustrating.

Kostas
