### ISSUE TITLE
Could not broadcast input array from shape (32,32,32) into shape (1)

### ISSUE THREAD

**Issue by alessando-guida** [Kamnitsask/deepmedic#166]
Hi Kostas,

I am getting a ValueError at start of training that is kind of similar to what was previously reported in #70 .

```
....
[JOB:46|PID:22768] Got samples per category: [Class-0: 10/10] [Class-1: 10/10] 
[JOB:47|PID:22768] Load & sample from subject of index (in user's list): 119 (Job #47/50)
[JOB:47|PID:22768] Loading subject with 1st channel at: /home/jupyter/dataset/preprocessed/PREDICT_04-029_Followup.nii
[JOB:47|PID:22768] Got samples per category: [Class-0: 10/10] [Class-1: 10/10] 
[JOB:48|PID:22768] Load & sample from subject of index (in user's list): 130 (Job #48/50)
[JOB:48|PID:22768] Loading subject with 1st channel at: /home/jupyter/dataset/preprocessed/PREDICT_05-022_Baseline.nii
[JOB:48|PID:22768] Got samples per category: [Class-0: 10/10] [Class-1: 10/10] 
[JOB:49|PID:22768] Load & sample from subject of index (in user's list): 86 (Job #49/50)
[JOB:49|PID:22768] Loading subject with 1st channel at: /home/jupyter/dataset/preprocessed/PREDICT_01-093_Baseline.nii
[JOB:49|PID:22768] Got samples per category: [Class-0: 10/10] [Class-1: 10/10] 
[SAMPLER-TR|PID:22768] TIMING: Sampling for next [Training] lasted: 79.8 secs.
[SAMPLER-TR|PID:22768] :=:=:=:=:=:=: Finished sampling for next [Training] :=:=:=:=:=:=:

 ERROR: Caught exception in do_training(): could not broadcast input array from shape (32,32,32) into shape (1)

Traceback (most recent call last):
  File "/home/jupyter/deepmedic/deepmedic/routines/training.py", line 305, in do_training
    labelsForCentralOfSegmentsForSubepTrain] = parallelJobToGetDataForNextTraining.get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
ValueError: could not broadcast input array from shape (32,32,32) into shape (1
```

I am using inputs and ground truth of similar shape within subjects, but with a different 3rd dimension between subjects. Do you have any suggestions on how to troubleshoot this issue? 

Thanks in advance

Alex

**Comment by alessando-guida** [comment]
I changed  the parameter ```num_processes_sampling = -1``` in the training configuration file, hopefully, this log message is more helpful to figure out the problem:

```
....
[JOB:49|PID:29491] Got samples per category: [Class-0: 10/10] [Class-1: 10/10] 
[SAMPLER-TR|PID:29491] TIMING: Sampling for next [Training] lasted: 80.9 secs.
[SAMPLER-TR|PID:29491] :=:=:=:=:=:=: Finished sampling for next [Training] :=:=:=:=:=:=:


 ERROR: Caught exception in do_training(): could not broadcast input array from shape (32,32,32) into shape (1)

Traceback (most recent call last):
  File "/home/jupyter/deepmedic/deepmedic/routines/training.py", line 295, in do_training
    labelsForCentralOfSegmentsForSubepTrain] = getSampledDataAndLabelsForSubepoch( *args_for_sampling_train )
  File "/home/jupyter/deepmedic/deepmedic/dataManagement/sampling.py", line 170, in getSampledDataAndLabelsForSubepoch
    channelsOfSegmentsForSubepochArrayPerPathway = [ np.asarray(imPartsForPathwayi, dtype="float32") for imPartsForPathwayi in channelsOfSegmentsForSubepochListPerPathway ]
  File "/usr/local/lib/python2.7/site-packages/numpy/core/numeric.py", line 501, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: could not broadcast input array from shape (32,32,32) into shape (1)
```

**Comment by alessando-guida** [comment]
it looks like I have in the dataset one subject with the dimension of one of the axes smaller (512x512x30) than the segment I specified in the configuration (32x32x32). I will try to set all the input shapes to (200x200x200). Hopefully, this will fix it.

**Comment by alessando-guida** [comment]
that fixed the problem.

**Comment by samieti02** [comment]
I have also observed this error many times.

> could not broadcast input array from shape (33,33,33) into shape (1)

```
ERROR: Caught exception in do_training(): could not broadcast input array from shape (33,33,33) into shape (1)
2019-7-3 2:17:18.66: Traceback (most recent call last):
  File "/deepmedic_wide/deepmedic/routines/training.py", line 292, in do_training    
	labelsForCentralOfSegmentsForSubepTrain) = parallelJobToGetDataForNextTraining.get()
File "/opt/conda/envs/dm_tf/lib/python3.6/multiprocessing/pool.py", line 644, in get
	raise self._value
File "/opt/conda/envs/dm_tf/lib/python3.6/multiprocessing/pool.py", line 119, in worker
	result = (True, func(*args, **kwds))
File "/deepmedic_wide/deepmedic/dataManagement/sampling.py", line 165, in getSampledDataAndLabelsForSubepoch
	channs_of_samples_arr_per_path = [ np.asarray(channs_of_samples_for_path, dtype="float32") for channs_of_samples_for_path in channs_of_samples_per_path_for_subep ]
  
File "/deepmedic_wide/deepmedic/dataManagement/sampling.py", line 165, in <listcomp>
	channs_of_samples_arr_per_path = [ np.asarray(channs_of_samples_for_path, dtype="float32") for channs_of_samples_for_path in channs_of_samples_per_path_for_subep ]
File "/opt/conda/envs/dm_tf/lib/python3.6/site-packages/numpy/core/numeric.py", line 492, in asarray
	return array(a, dtype, copy=False, order=order)
ValueError: could not broadcast input array from shape (33,33,33) into shape (1)
2019-7-3 2:17:18.66: Terminating worker pool.
```

The last time , the process was at epoch 57 (of 100) and I have images of size 95x95x95 It sometimes annoying, because you dont know exactly, what causes that and also dont know if the process will run till the end without error.
