### ISSUE TITLE
Training Fails After Loading Subjects

### ISSUE THREAD

**Issue by AyushKarnawat** [Kamnitsask/deepmedic#17]
Hi Kamnitsask,

I am getting this error that the deepMedicRun program is not running properly. This happens during training of Epoch#0, Subepoch#0 (as seen below) after all the necessary subjects have been loaded. 

This same code was previously working on other training + testing sets we performed, yet today it is giving this error. I have attached the error output for reference below.

Best,
Ayush

```python
TIMING: Extracting all the Segments for next Training took time: 110.04(s)
:=:=:=:=:=:=:=:=: Finished extracting Segments from the images for next Training. :=:=:=:=:=:=:=:=:
Loading Training data for subepoch #0 on shared variable...
TIMING: Loading sharedVariables for Training in epoch|subepoch=0|0 took time: 0.14(s)
PARALLEL: Before Training in subepoch #0, submitting the parallel job for extracting Segments for the next Validation.
-T-T-T-T-T- Now Training for this subepoch... This may take a few minutes... -T-T-T-T-T-
Trained on 0/100 of the batches for this subepoch...
Traceback (most recent call last):
  File "/home/axk840/deepmedic/deepMedicRun", line 102, in <module>
    deepMedicTrain.deepMedicTrainMain(absPathToTrainConf, absPathToCnnModelGivenInCmdLine, cnnInstanceLoaded, filenameAndPathWhereNewlyCreatedModelWasSaved)
  File "/home/axk840/deepmedic/deepmedic/frontEndModules/deepMedicTrain.py", line 440, in deepMedicTrainMain
    do_training(*trainSessionParameters.getTupleForCnnTraining())
  File "/home/axk840/deepmedic/deepmedic/trainValidateTestVisualiseParallel.py", line 1500, in do_training
    subepoch)
  File "/home/axk840/deepmedic/deepmedic/trainValidateTestVisualiseParallel.py", line 1029, in doTrainOrValidationOnBatchesAndReturnMeanAccuraciesOfSubepoch
    listWithCostMeanErrorAndRpRnTpTnForEachClassFromTraining = cnn3dInstance.cnnTrainModel(batch_i, vectorWithWeightsOfTheClassesForCostFunctionOfTraining)
  File "/home/axk840/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py", line 875, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/axk840/anaconda2/lib/python2.7/site-packages/theano/gof/link.py", line 317, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/axk840/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py", line 862, in __call__
    self.fn() if output_subset is None else\
  File "/home/axk840/anaconda2/lib/python2.7/site-packages/theano/gof/op.py", line 905, in rval
    r = p(n, [x[0] for x in i], o)
  File "/home/axk840/anaconda2/lib/python2.7/site-packages/theano/tensor/subtensor.py", line 2167, in perform
    out[0] = inputs[0].__getitem__(inputs[1:])
IndexError: index 6 is out of bounds for axis 1 with size 5
Apply node that caused the error: AdvancedSubtensor(HostFromGpu.0, ARange{dtype='int64'}.0, Elemwise{Cast{int32}}.0)
Toposort index: 1857
Inputs types: [TensorType(float32, matrix), TensorType(int64, vector), TensorType(int32, vector)]
Inputs shapes: [(7290, 5), (7290,), (7290,)]
Inputs strides: [(20, 4), (8,), (4,)]
Inputs values: ['not shown', 'not shown', 'not shown']
Outputs clients: [[Sum{acc_dtype=float64}(AdvancedSubtensor.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "/home/axk840/deepmedic/deepMedicRun", line 95, in <module>
    (cnnInstanceLoaded, filenameAndPathWhereNewlyCreatedModelWasSaved) = deepMedicNewModel.deepMedicNewModelMain(absPathToModelConf)
  File "/home/axk840/deepmedic/deepmedic/frontEndModules/deepMedicNewModel.py", line 192, in deepMedicNewModelMain
    cnn3dInstance.make_cnn_model(*createModelSessionParameters.getTupleForCnnCreation())
  File "/home/axk840/deepmedic/deepmedic/cnn3d.py", line 1242, in make_cnn_model
    costFunctionLetter)
  File "/home/axk840/deepmedic/deepmedic/cnn3d.py", line 602, in compileNewTrainFunction
    costFunctionFromLastLayer = self.fcLayers[-1].negativeLogLikelihood(y, weightsOfClassesInCostFunction)
  File "/home/axk840/deepmedic/deepmedic/cnnLayerTypes.py", line 265, in negativeLogLikelihood
    return -T.mean( weighted_logOf_p_y_given_x[T.arange(y.shape[0]), y] )

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

**Comment by Kamnitsask** [comment]
I believe you have configured the modelConfig for 5 classes and one of your images has a label == 6. Your GT label-images much not have any value > numberOfClasses.

Check that out and let me know how it goes.

Kostas

**Comment by AyushKarnawat** [comment]
Hi Kostas,

So actually I realized that I had the same problem as ChenFeiL where by mistake, I normalized the GT labels. As such, it threw the same error. That fixed the problem, but thank you for your help anyways.

Ayush
