### ISSUE TITLE
Training error :ERROR: Caught exception in getSampledDataAndLabelsForSubepoch():

### ISSUE THREAD

**Issue by aliamani72** [Kamnitsask/deepmedic#173]
Hi
Dear Mr. Konstantinos
I am working Ischemic Stroke Lesion segmentation by using  deepMedic on ISLES2015 database.I installed deepmedic and  did the steps to test it on the instructions and it worked well. But when I try runinig it for a data example of the ISLES2015 in the training phase  , I encounter the following error. What is the reason for this problem?What parameter should I change?Thank you very much!
---------------------------------------------------------------------------------------------
Given configuration file:  C:\Users\Soheil System\deepmedic\examples\configFiles\isles\model\modelConfig.cfg
Given configuration file:  C:\Users\Soheil System\deepmedic\examples\configFiles\isles\train\trainConfig.cfg
Creating necessary folders for training session...
=============================== logger created =======================================

======================== Starting new session ============================
Command line arguments given:
Namespace(device='cpu', model_cfg='./examples/configFiles/isles/model/modelConfig.cfg', reset_trainer=False, saved_model=None, test_cfg=None, train_cfg='examples/configFiles/isles/train/trainConfig.cfg')
2019-06-26 21:06:14.143553: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Available devices to Tensorflow:
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 18444724726637146141
]
CONFIG: The configuration file for the [model] given is: C:\Users\Soheil System\deepmedic\examples\configFiles\isles\model\modelConfig.cfg
=============================================================
========== PARAMETERS FOR MAKING THE ARCHITECTURE ===========
=============================================================
CNN model's name = deepMedic
~~~~~~~~~~~~~~~~~~Model parameters~~~~~~~~~~~~~~~~
Number of Classes (including background) = 5
~~Normal Pathway~~
Number of Input Channels = 2
Number of Layers = 8
Number of Feature Maps per layer = [30, 30, 40, 40, 40, 40, 50, 50]
Kernel Dimensions per layer = [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]
Receptive Field = [17, 17, 17]
Residual connections added at the output of layers (indices from 0) = [3, 5, 7]
Layers that will be made of Lower Rank (indices from 0) = []
Lower Rank layers will be made of rank = []
~~Subsampled Pathway~~
Use subsampled Pathway = True
Number of subsampled pathways that will be built = 2
Number of Layers (per sub-pathway) = [8, 8]
Number of Feature Maps per layer (per sub-pathway) = [[30, 30, 40, 40, 40, 40, 50, 50], [30, 30, 40, 40, 40, 40, 50, 50]]
Kernel Dimensions per layer = [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]
Receptive Field = [17, 17, 17]
Subsampling Factor per dimension (per sub-pathway) = [[3, 3, 3], [5, 5, 5]]
Residual connections added at the output of layers (indices from 0) = [3, 5, 7]
Layers that will be made of Lower Rank (indices from 0) = []
Lower Rank layers will be made of rank = []
~~Fully Connected Pathway~~
Number of additional FC layers (Excluding the Classif. Layer) = 2
Number of Feature Maps in the additional FC layers = [250, 250]
Residual connections added at the output of layers (indices from 0) = [1]
Layers that will be made of Lower Rank (indices from 0) = []
Dimensions of Kernels in the 1st FC layer (Classif. layer if no hidden FCs used) = [3, 3, 3]
~~Size Of Image Segments~~
Size of Segments for Training = [37, 37, 37]
Size of Segments for Validation = [17, 17, 17]
Size of Segments for Testing = [45, 45, 45]
~~Batch Sizes~~
Batch Size for Training = 10
Batch Size for Validation = 48
Batch Size for Testing = 10
~~Dropout Rates~~
Drop.R. for each layer in Normal Pathway = []
Drop.R. for each layer in Subsampled Pathway = []
Drop.R. for each layer in FC Pathway (additional FC layers + Classific.Layer at end) = [0.0, 0.5, 0.5]
~~Weight Initialization~~
Initialization method and params for the conv kernel weights = ['fanIn', 2]
~~Activation Function~~
Activation function to use = prelu
~~Batch Normalization~~
Apply BN straight on pathways' inputs (eg straight on segments) = [False, False, True]
Batch Normalization uses a rolling average for inference, over this many batches = 60
========== Done with printing session's parameters ==========
=============================================================
CONFIG: The configuration file for the [session] was loaded from: C:\Users\Soheil System\deepmedic\examples\configFiles\isles\train\trainConfig.cfg

=============   NEW TRAINING SESSION     ==============


=============================================================
========= PARAMETERS FOR THIS TRAINING SESSION ==============
=============================================================
Session's name = trainSessionDm
Model will be loaded from save = None
~~Output~~
Main output folder = C:\Users\Soheil System\deepmedic\examples\output
Path and filename to save trained models = C:\Users\Soheil System\deepmedic\examples\output/saved_models//trainSessionDm//deepMedic.trainSessionDm
~~~~~~~~~~~~~~~~~~Generic Information~~~~~~~~~~~~~~~~
Number of Cases for Training = 2
Number of Cases for Validation = 2
~~~~~~~~~~~~~~~~~~Training parameters~~~~~~~~~~~~~~~~
Filepaths to Channels of the Training Cases = [['C:\\Users\\Soheil System\\deepmedic\\examples\\dataForExamples\\isls\\train\\1\\f.nii.gz', 'C:\\Users\\Soheil System\\deepmedic\\examples\\dataForExamples\\isls\\train\\1\\t.nii.gz'], ['C:\\Users\\Soheil System\\deepmedic\\examples\\dataForExamples\\isls\\train\\2\\f.nii.gz', 'C:\\Users\\Soheil System\\deepmedic\\examples\\dataForExamples\\isls\\train\\2\\t.nii.gz']]
Filepaths to Ground-Truth labels of the Training Cases = ['C:\\Users\\Soheil System\\deepmedic\\examples\\dataForExamples\\isls\\train\\1\\l.nii.gz', 'C:\\Users\\Soheil System\\deepmedic\\examples\\dataForExamples\\isls\\train\\2\\l.nii.gz']
~~Sampling~~
Region-Of-Interest Masks provided = True
Filepaths to ROI Masks of the Training Cases = ['C:\\Users\\Soheil System\\deepmedic\\examples\\dataForExamples\\isls\\train\\1\\mask brain.nii.gz', 'C:\\Users\\Soheil System\\deepmedic\\examples\\dataForExamples\\isls\\train\\2\\mask brain.nii.gz']
~~Advanced Sampling~~
Using default sampling = True. NOTE: Adv.Sampl.Params are auto-set to perform default sampling if True.
Type of Sampling = Fore/Background (0)
Sampling Categories = ['Foreground', 'Background']
Percent of Samples to extract per Sampling Category = [0.5 0.5]
Provided Weight-Maps, pointing where to focus sampling for each category (if False, samples will be extracted based on GT and ROI) = False
Paths to weight-maps for sampling of each category = None
~~Training Cycle~~
Number of Epochs = 35
Number of Subepochs per epoch = 20
Number of cases to load per Subepoch (for extracting the samples for this subepoch) = 50
Number of Segments loaded on GPU per subepoch for Training = 1000. NOTE: This number of segments divided by the batch-size defines the number of optimization-iterations that will be performed every subepoch!
Number of parallel processes for sampling = 0
~~Learning Rate Schedule~~
Type of schedule = predef
[Predef] Predefined schedule of epochs when the LR will be lowered = [17, 22, 27, 30, 33]
[Predef] When decreasing Learning Rate, divide LR by = 2.0
[Poly] Initial epochs to wait before lowering LR = 10
[Poly] Final epoch for the schedule = 35
[Auto] Initial epochs to wait before lowering LR = 10
[Auto] When decreasing Learning Rate, divide LR by = 2.0
[Auto] Minimum increase in validation accuracy (0. to 1.) that resets the waiting counter = 0.0
[Expon] (Deprecated) parameters = {'epochs_wait_before_decr': 10, 'final_ep_for_sch': 35, 'lr_to_reach_at_last_ep': 0.00390625, 'mom_to_reach_at_last_ep': 0.9}
~~Data Augmentation During Training~~
Reflect images per axis = [False, False, False]
Perform intensity-augmentation [I'= (I+shift)*mult] = False
[Int. Augm.] Sample Shift from N(mu,std) = plcholder
[Int. Augm.] Sample Multi from N(mu,std) = []
[Int. Augm.] (DEBUGGING:) full parameters [ doIntAugm, shift, mult] = [False, 'plcholder', [], []]
~~~~~~~~~~~~~~~~~~Validation parameters~~~~~~~~~~~~~~~~
Perform Validation on Samples throughout training? = True
Perform Full Inference on validation cases every few epochs? = True
Filepaths to Channels of the Validation Cases (Req for either of the above) = [['C:\\Users\\Soheil System\\deepmedic\\examples\\dataForExamples\\isls\\validation\\1\\f.nii.gz', 'C:\\Users\\Soheil System\\deepmedic\\examples\\dataForExamples\\isls\\validation\\1\\t.nii.gz'], ['C:\\Users\\Soheil System\\deepmedic\\examples\\dataForExamples\\isls\\validation\\2\\f.nii.gz', 'C:\\Users\\Soheil System\\deepmedic\\examples\\dataForExamples\\isls\\validation\\2\\t.nii.gz']]
Provided Ground-Truth for Validation = True. NOTE: Required for Val on samples. Not Req for Full-Inference, but DSC will be reported if provided.
Filepaths to Ground-Truth labels of the Validation Cases = ['C:\\Users\\Soheil System\\deepmedic\\examples\\dataForExamples\\isls\\validation\\1\\l.nii.gz', 'C:\\Users\\Soheil System\\deepmedic\\examples\\dataForExamples\\isls\\validation\\2\\l.nii.gz']
Provided ROI masks for Validation = True. NOTE: Validation-sampling and Full-Inference will be limited within this mask if provided. If not provided, Negative Validation samples will be extracted from whole volume, except if advanced-sampling is enabled, and the user provided separate weight-maps for sampling.
Filepaths to ROI masks for Validation Cases = ['C:\\Users\\Soheil System\\deepmedic\\examples\\dataForExamples\\isls\\validation\\1\\mask brain.nii.gz', 'C:\\Users\\Soheil System\\deepmedic\\examples\\dataForExamples\\isls\\validation\\2\\mask brain.nii.gz']
~~~~~~~Validation on Samples throughout Training~~~~~~~
Number of Segments loaded on GPU per subepoch for Validation = 5000
~~Advanced Sampling~~
Using default uniform sampling for validation = True. NOTE: Adv.Sampl.Params are auto-set to perform uniform-sampling if True.
Type of Sampling = Uniform (1)
Sampling Categories = ['Uniform']
Percent of Samples to extract per Sampling Category = [1.0]
Provided Weight-Maps, pointing where to focus sampling for each category (if False, samples will be extracted based on GT and ROI) = False
Paths to weight-maps for sampling of each category = None
~~~~~Validation with Full Inference on Validation Cases~~~~~
Perform Full-Inference on Val. cases every that many epochs = 5
~~Predictions (segmentations and prob maps on val. cases)~~
Save Segmentations = True
Save Probability Maps for each class = [True, True, True, True, True]
Filepaths to save results per case = ['C:\\Users\\Soheil System\\deepmedic\\examples\\output/predictions/trainSessionDm/predictions//isles_1.nii.gz', 'C:\\Users\\Soheil System\\deepmedic\\examples\\output/predictions/trainSessionDm/predictions//isles_2.nii.gz']
Suffixes with which to save segmentations and probability maps = {'segm': 'Segm', 'prob': 'ProbMapClass'}
~~Feature Maps~~
Save Feature Maps = False
Save FMs in a 4D-image = False
Min/Max Indices of FMs to visualise per pathway-type and per layer = None
Filepaths to save FMs per case = ['C:\\Users\\Soheil System\\deepmedic\\examples\\output/predictions/trainSessionDm/features//isles_1.nii.gz', 'C:\\Users\\Soheil System\\deepmedic\\examples\\output/predictions/trainSessionDm/features//isles_2.nii.gz']
~~Optimization~~
Initial Learning rate = 0.001
Optimizer to use: SGD(0), Adam(1), RmsProp(2) = 2
Parameters for Adam: b1= placeholder, b2=placeholder, e= placeholder
Parameters for RmsProp: rho= 0.9, e= 0.0001
Momentum Type: Classic (0) or Nesterov (1) = 1
Momentum Non-Normalized (0) or Normalized (1) = 0
Momentum Value = 0.6
~~Costs~~
Loss functions and their weights = {'xentr': 1.0, 'iou': None, 'dsc': None}
Reweight samples in cost on a per-class basis = {'type': None, 'prms': None, 'schedule': [0, 35]}
L1 Regularization term = 1e-06
L2 Regularization term = 0.0001
~~Freeze Weights of Certain Layers~~
Indices of layers from each type of pathway that will be kept fixed (first layer is 0):
Normal pathway's layers to freeze = []
Subsampled pathway's layers to freeze = []
FC pathway's layers to freeze = []
~~~~~~~~~~~~~~~~~~Other Generic Parameters~~~~~~~~~~~~~~~~
Check whether input data has correct format (can slow down process) = True
~~Pre Processing~~
Pad Input Images = True
========== Done with printing session's parameters ==========
=============================================================

=======================================================

=========== Making the CNN graph... ===============
...Building the CNN model...
[Pathway_NORMAL] is being built...
        [Pathway_NORMAL]: Input's Shape: (Train) [10, 2, 37, 37, 37], (Val) [48, 2, 17, 17, 17], (Test) [10, 2, 45, 45, 45]
        [Conv.Layer_0], Filter Shape: [30, 2, 3, 3, 3]
        [Conv.Layer_0], Input's Shape: (Train) [10, 2, 37, 37, 37], (Val) [48, 2, 17, 17, 17], (Test) [10, 2, 45, 45, 45]
        [Conv.Layer_1], Filter Shape: [30, 30, 3, 3, 3]
        [Conv.Layer_1], Input's Shape: (Train) [10, 30, 35, 35, 35], (Val) [48, 30, 15, 15, 15], (Test) [10, 30, 43, 43, 43]
        [Conv.Layer_2], Filter Shape: [40, 30, 3, 3, 3]
        [Conv.Layer_2], Input's Shape: (Train) [10, 30, 33, 33, 33], (Val) [48, 30, 13, 13, 13], (Test) [10, 30, 41, 41, 41]
        [Conv.Layer_3], Filter Shape: [40, 40, 3, 3, 3]
        [Conv.Layer_3], Input's Shape: (Train) [10, 40, 31, 31, 31], (Val) [48, 40, 11, 11, 11], (Test) [10, 40, 39, 39, 39]
        [Pathway_NORMAL]: making Residual Connection between output of [Layer_3] to input of previous layer.
        [Conv.Layer_4], Filter Shape: [40, 40, 3, 3, 3]
        [Conv.Layer_4], Input's Shape: (Train) [10, 40, 29, 29, 29], (Val) [48, 40, 9, 9, 9], (Test) [10, 40, 37, 37, 37]
        [Conv.Layer_5], Filter Shape: [40, 40, 3, 3, 3]
        [Conv.Layer_5], Input's Shape: (Train) [10, 40, 27, 27, 27], (Val) [48, 40, 7, 7, 7], (Test) [10, 40, 35, 35, 35]
        [Pathway_NORMAL]: making Residual Connection between output of [Layer_5] to input of previous layer.
        [Conv.Layer_6], Filter Shape: [50, 40, 3, 3, 3]
        [Conv.Layer_6], Input's Shape: (Train) [10, 40, 25, 25, 25], (Val) [48, 40, 5, 5, 5], (Test) [10, 40, 33, 33, 33]
        [Conv.Layer_7], Filter Shape: [50, 50, 3, 3, 3]
        [Conv.Layer_7], Input's Shape: (Train) [10, 50, 23, 23, 23], (Val) [48, 50, 3, 3, 3], (Test) [10, 50, 31, 31, 31]
        [Pathway_NORMAL]: making Residual Connection between output of [Layer_7] to input of previous layer.
        [Pathway_NORMAL]: Output's Shape: (Train) [10, 50, 21, 21, 21], (Val) [48, 50, 1, 1, 1], (Test) [10, 50, 29, 29, 29]
[Pathway_NORMAL] done.
[Pathway_SUBSAMPLED[3, 3, 3]] is being built...
        [Pathway_SUBSAMPLED[3, 3, 3]]: Input's Shape: (Train) [10, 2, 23, 23, 23], (Val) [48, 2, 17, 17, 17], (Test) [10, 2, 26, 26, 26]
        [Conv.Layer_0], Filter Shape: [30, 2, 3, 3, 3]
        [Conv.Layer_0], Input's Shape: (Train) [10, 2, 23, 23, 23], (Val) [48, 2, 17, 17, 17], (Test) [10, 2, 26, 26, 26]
        [Conv.Layer_1], Filter Shape: [30, 30, 3, 3, 3]
        [Conv.Layer_1], Input's Shape: (Train) [10, 30, 21, 21, 21], (Val) [48, 30, 15, 15, 15], (Test) [10, 30, 24, 24, 24]
        [Conv.Layer_2], Filter Shape: [40, 30, 3, 3, 3]
        [Conv.Layer_2], Input's Shape: (Train) [10, 30, 19, 19, 19], (Val) [48, 30, 13, 13, 13], (Test) [10, 30, 22, 22, 22]
        [Conv.Layer_3], Filter Shape: [40, 40, 3, 3, 3]
        [Conv.Layer_3], Input's Shape: (Train) [10, 40, 17, 17, 17], (Val) [48, 40, 11, 11, 11], (Test) [10, 40, 20, 20, 20]
        [Pathway_SUBSAMPLED[3, 3, 3]]: making Residual Connection between output of [Layer_3] to input of previous layer.
        [Conv.Layer_4], Filter Shape: [40, 40, 3, 3, 3]
        [Conv.Layer_4], Input's Shape: (Train) [10, 40, 15, 15, 15], (Val) [48, 40, 9, 9, 9], (Test) [10, 40, 18, 18, 18]
        [Conv.Layer_5], Filter Shape: [40, 40, 3, 3, 3]
        [Conv.Layer_5], Input's Shape: (Train) [10, 40, 13, 13, 13], (Val) [48, 40, 7, 7, 7], (Test) [10, 40, 16, 16, 16]
        [Pathway_SUBSAMPLED[3, 3, 3]]: making Residual Connection between output of [Layer_5] to input of previous layer.
        [Conv.Layer_6], Filter Shape: [50, 40, 3, 3, 3]
        [Conv.Layer_6], Input's Shape: (Train) [10, 40, 11, 11, 11], (Val) [48, 40, 5, 5, 5], (Test) [10, 40, 14, 14, 14]
        [Conv.Layer_7], Filter Shape: [50, 50, 3, 3, 3]
        [Conv.Layer_7], Input's Shape: (Train) [10, 50, 9, 9, 9], (Val) [48, 50, 3, 3, 3], (Test) [10, 50, 12, 12, 12]
        [Pathway_SUBSAMPLED[3, 3, 3]]: making Residual Connection between output of [Layer_7] to input of previous layer.
        [Pathway_SUBSAMPLED[3, 3, 3]]: Output's Shape: (Train) [10, 50, 7, 7, 7], (Val) [48, 50, 1, 1, 1], (Test) [10, 50, 10, 10, 10]
[Pathway_SUBSAMPLED[3, 3, 3]] done.
[Pathway_SUBSAMPLED[5, 5, 5]] is being built...
        [Pathway_SUBSAMPLED[5, 5, 5]]: Input's Shape: (Train) [10, 2, 21, 21, 21], (Val) [48, 2, 17, 17, 17], (Test) [10, 2, 22, 22, 22]
        [Conv.Layer_0], Filter Shape: [30, 2, 3, 3, 3]
        [Conv.Layer_0], Input's Shape: (Train) [10, 2, 21, 21, 21], (Val) [48, 2, 17, 17, 17], (Test) [10, 2, 22, 22, 22]
        [Conv.Layer_1], Filter Shape: [30, 30, 3, 3, 3]
        [Conv.Layer_1], Input's Shape: (Train) [10, 30, 19, 19, 19], (Val) [48, 30, 15, 15, 15], (Test) [10, 30, 20, 20, 20]
        [Conv.Layer_2], Filter Shape: [40, 30, 3, 3, 3]
        [Conv.Layer_2], Input's Shape: (Train) [10, 30, 17, 17, 17], (Val) [48, 30, 13, 13, 13], (Test) [10, 30, 18, 18, 18]
        [Conv.Layer_3], Filter Shape: [40, 40, 3, 3, 3]
        [Conv.Layer_3], Input's Shape: (Train) [10, 40, 15, 15, 15], (Val) [48, 40, 11, 11, 11], (Test) [10, 40, 16, 16, 16]
        [Pathway_SUBSAMPLED[5, 5, 5]]: making Residual Connection between output of [Layer_3] to input of previous layer.
        [Conv.Layer_4], Filter Shape: [40, 40, 3, 3, 3]
        [Conv.Layer_4], Input's Shape: (Train) [10, 40, 13, 13, 13], (Val) [48, 40, 9, 9, 9], (Test) [10, 40, 14, 14, 14]
        [Conv.Layer_5], Filter Shape: [40, 40, 3, 3, 3]
        [Conv.Layer_5], Input's Shape: (Train) [10, 40, 11, 11, 11], (Val) [48, 40, 7, 7, 7], (Test) [10, 40, 12, 12, 12]
        [Pathway_SUBSAMPLED[5, 5, 5]]: making Residual Connection between output of [Layer_5] to input of previous layer.
        [Conv.Layer_6], Filter Shape: [50, 40, 3, 3, 3]
        [Conv.Layer_6], Input's Shape: (Train) [10, 40, 9, 9, 9], (Val) [48, 40, 5, 5, 5], (Test) [10, 40, 10, 10, 10]
        [Conv.Layer_7], Filter Shape: [50, 50, 3, 3, 3]
        [Conv.Layer_7], Input's Shape: (Train) [10, 50, 7, 7, 7], (Val) [48, 50, 3, 3, 3], (Test) [10, 50, 8, 8, 8]
        [Pathway_SUBSAMPLED[5, 5, 5]]: making Residual Connection between output of [Layer_7] to input of previous layer.
        [Pathway_SUBSAMPLED[5, 5, 5]]: Output's Shape: (Train) [10, 50, 5, 5, 5], (Val) [48, 50, 1, 1, 1], (Test) [10, 50, 6, 6, 6]
[Pathway_SUBSAMPLED[5, 5, 5]] done.
DEBUG: Shape of the kernel of the first FC layer is : [3, 3, 3]
DEBUG: Input to the FC Pathway will be padded by that many voxels per dimension: [2, 2, 2]
[Pathway_FC] is being built...
        [Pathway_FC]: Input's Shape: (Train) [10, 150, 23, 23, 23], (Val) [48, 150, 3, 3, 3], (Test) [10, 150, 31, 31, 31]
        [Conv.Layer_0], Filter Shape: [250, 150, 3, 3, 3]
        [Conv.Layer_0], Input's Shape: (Train) [10, 150, 23, 23, 23], (Val) [48, 150, 3, 3, 3], (Test) [10, 150, 31, 31, 31]
        [Conv.Layer_1], Filter Shape: [250, 250, 1, 1, 1]
        [Conv.Layer_1], Input's Shape: (Train) [10, 250, 21, 21, 21], (Val) [48, 250, 1, 1, 1], (Test) [10, 250, 29, 29, 29]
        [Pathway_FC]: making Residual Connection between output of [Layer_1] to input of previous layer.
        [Conv.Layer_2], Filter Shape: [5, 250, 1, 1, 1]
        [Conv.Layer_2], Input's Shape: (Train) [10, 250, 21, 21, 21], (Val) [48, 250, 1, 1, 1], (Test) [10, 250, 29, 29, 29]
        [Pathway_FC]: Output's Shape: (Train) [10, 5, 21, 21, 21], (Val) [48, 5, 1, 1, 1], (Test) [10, 5, 29, 29, 29]
[Pathway_FC] done.
Adding the final Softmax Target layer...
Finished building the CNN's model.
=========== Building Trainer ===========

Building Trainer.
COST: Using cross entropy with weight: 1.0
...Initializing state of the optimizer...
=========== Compiling the Training Function ===========
=======================================================

...Building the training function...
...Collecting ops and feeds for training...
Done.
=========== Compiling the Validation Function =========
...Building the validation function...
...Collecting ops and feeds for validation...
Done.
=========== Compiling the Testing Function ============
...Building the function for testing and visualisation of FMs...
...Collecting ops and feeds for testing...
Done.
=========== Initializing network and trainer variables  ===============
All variables were initialized.
Saving the initial model at:C:\Users\Soheil System\deepmedic\examples\output/saved_models//trainSessionDm//deepMedic.trainSessionDm.initial.2019-06-26.21.06.51.674886

=======================================================
============== Training the CNN model =================
=======================================================

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~    Starting new Epoch! Epoch #0/35        ~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
***************************************************************************************
*******          Starting new Subepoch: #0/20           ********
***************************************************************************************
[MAIN|PID:16888] MULTIPROC: Before Validation in subepoch #0, submitting sampling job for next [VALIDATION].
[SAMPLER-VAL|PID:16888] :=:=:=:=:=:=: Starting to sample for next [Validation]... :=:=:=:=:=:=:
[SAMPLER-VAL|PID:16888] Out of [2] subjects given for [Validation], we will sample from maximum [50] per subepoch.
[SAMPLER-VAL|PID:16888] Shuffled indices of subjects that were randomly chosen: [1, 0]
[SAMPLER-VAL|PID:16888] Will sample from [2] subjects for next Validation...
[JOB:1|PID:16888] Load & sample from subject of index (in user's list): 1 (Job #1/2)
[JOB:1|PID:16888] Loading subject with 1st channel at: C:\Users\Soheil System\deepmedic\examples\dataForExamples\isls\validation\2\f.nii.gz
[SAMPLER-VAL|PID:16888]

 ERROR: Caught exception in getSampledDataAndLabelsForSubepoch():

Traceback (most recent call last):
  File "C:\Users\Soheil System\deepmedic\deepmedic\dataManagement\sampling.py", line 128, in getSampledDataAndLabelsForSubepoch
    lblsOfPredictedPartOfSegmentsFromThisSubj) = load_subj_and_get_samples( *args_sampling_job )
  File "C:\Users\Soheil System\deepmedic\deepmedic\dataManagement\sampling.py", line 303, in load_subj_and_get_samples
    reflectImageWithHalfProb = reflectImageWithHalfProbDuringTraining )
  File "C:\Users\Soheil System\deepmedic\deepmedic\dataManagement\sampling.py", line 411, in load_imgs_of_subject
    roiMask = loadVolume(fullFilenamePathOfRoiMask)
  File "C:\Users\Soheil System\deepmedic\deepmedic\image\io.py", line 30, in loadVolume
    assert img.shape[3] > 1
AssertionError

 ERROR: Caught exception in do_training():

Traceback (most recent call last):
  File "C:\Users\Soheil System\deepmedic\deepmedic\routines\training.py", line 271, in do_training
    labelsForCentralOfSegmentsForSubepVal] = parallelJobToGetDataForNextValidation.get()
  File "D:\anaconda\envs\tensorflow\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
  File "D:\anaconda\envs\tensorflow\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Soheil System\deepmedic\deepmedic\dataManagement\sampling.py", line 167, in getSampledDataAndLabelsForSubepoch
    raise e
  File "C:\Users\Soheil System\deepmedic\deepmedic\dataManagement\sampling.py", line 128, in getSampledDataAndLabelsForSubepoch
    lblsOfPredictedPartOfSegmentsFromThisSubj) = load_subj_and_get_samples( *args_sampling_job )
  File "C:\Users\Soheil System\deepmedic\deepmedic\dataManagement\sampling.py", line 303, in load_subj_and_get_samples
    reflectImageWithHalfProb = reflectImageWithHalfProbDuringTraining )
  File "C:\Users\Soheil System\deepmedic\deepmedic\dataManagement\sampling.py", line 411, in load_imgs_of_subject
    roiMask = loadVolume(fullFilenamePathOfRoiMask)
  File "C:\Users\Soheil System\deepmedic\deepmedic\image\io.py", line 30, in loadVolume
    assert img.shape[3] > 1
AssertionError

Terminating worker pool.

=======================================================
=========== Training session finished =================
=======================================================
Finished.

**Comment by Kamnitsask** [comment]
Hello, sorry for the slow reply, busy with writing my PhD Thesis and I have to put everything else aside for a couple of months..

In this file:
```
System\deepmedic\deepmedic\image\io.py", line 30, in loadVolume
assert img.shape[3] > 1
AssertionError
```

Sorry, that assert above was supposed to be img.shape[3] == 1

Just fixed this in commit c10b67b on master

thanks
