### ISSUE TITLE
AttributeError when loading model for testing

### ISSUE THREAD

**Issue by csestili** [Kamnitsask/deepmedic#44]
Hello,

I have successfully trained a network, copied that network object to a different machine, and tested with that copied network on the second machine. The network that I tested on has 3 GPUs, and testing runs successfully on a Tesla K20c GPU.

When I try to use the same network on a third machine, with only one GPU (Quadro K4000), I get the following error message:

`=========== Loading the CNN model for testing... ===============
...Loading the network can take a few minutes if the model is big...
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release.  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 0: Quadro K4000 (CNMeM is disabled, cuDNN not available)
Traceback (most recent call last):
  File "/data/HDFT/pkg/deepmedic-master/deepMedicRun", line 109, in <module>
    deepMedicTest.deepMedicTestMain(absPathToTestConf, absPathToCnnModelGivenInCmdLine)
  File "/data/HDFT/pkg/deepmedic-master/deepmedic/frontEndModules/deepMedicTest.py", line 257, in deepMedicTestMain
    cnn3dInstance = load_object_from_gzip_file(filepathToCnnModelToLoad)
  File "/data/HDFT/pkg/deepmedic-master/deepmedic/genericHelpers.py", line 128, in load_object_from_gzip_file
    loaded_obj = cPickle.load(f)
  File "/data/HDFT/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/compile/function_module.py", line 1040, in _constructor_Function
    f = maker.create(input_storage, trustme=True)
  File "/data/HDFT/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/compile/function_module.py", line 1651, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/data/HDFT/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gof/link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "/data/HDFT/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gof/vm.py", line 1063, in make_all
    impl=impl))
  File "/data/HDFT/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gof/op.py", line 924, in make_thunk
    no_recycling)
  File "/data/HDFT/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gof/op.py", line 828, in make_c_thunk
    output_storage=node_output_storage)
  File "/data/HDFT/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gof/cc.py", line 1190, in make_thunk
    keep_lock=keep_lock)
  File "/data/HDFT/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gof/cc.py", line 1131, in __compile__
    keep_lock=keep_lock)
  File "/data/HDFT/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gof/cc.py", line 1589, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/data/HDFT/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gof/cmodule.py", line 1114, in module_from_key
    module = self._get_from_key(key)
  File "/data/HDFT/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gof/cmodule.py", line 1006, in _get_from_key
    if key in self.entry_from_key:
  File "/data/HDFT/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gof/utils.py", line 189, in __hash__
    tuple(getattr(self, a) for a in props)))
  File "/data/HDFT/lib/python2.7/site-packages/Theano-0.9.0b1-py2.7.egg/theano/gof/utils.py", line 189, in <genexpr>
    tuple(getattr(self, a) for a in props)))
AttributeError`

I do not get the CUDA deprecation warning on the other machines.

Any idea what is causing this error or how to fix it?

Thank you for your help!

**Comment by gourie** [comment]
Hi,

I had a similar issue recently when running Theano & DeepMedic on a new machine with one GTX1080.

Solution:
1 - compile the new dependency (libgpuarray)
2 - I recommend using the test script and check for error messages when using libgpuarray (my NVidia driver was too recent so I had force loading using environment variable specified in ERROR below)

```bash
# DEVICE='cuda0' python -c "import pygpu;pygpu.test()"
pygpu is installed in /opt/software/lib/anaconda27/lib/python2.7/site-packages/pygpu-0.6.1-py2.7-linux-x86_64.egg/pygpu
NumPy version 1.12.0
NumPy relaxed strides checking option: True
NumPy is installed in /opt/software/lib/anaconda27/lib/python2.7/site-packages/numpy
Python version 2.7.12 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:42:40) [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
nose version 1.3.7
ERROR: refusing to load cuda driver library because the version is blacklisted.  Versions 373.06 and below are known to be ok.
If you want to bypass this check and force the driver load define GPUARRAY_FORCE_CUDA_DRIVER_LOAD in your environement.
```

One minor note: I started from scratch on this new machine (first build new model, then train etc) so not quite your case...

Hope this helps for you!

gr,
Joeri

**Comment by Kamnitsask** [comment]
Hello,

In general, when you move models across machines, you may come across incompatibilities when CUDA/CuDnn versions differ and when Theano versions differ. In your case, probably it's the latter.

I am guessing you trained the model with Theano 0.8 and moved to a machine that has Theano 0.9?

I have not found time to look into the differences 0.9 brings and migrate. But the link provided in the error message states among others: replacing conv3d2d operator (currently used in deepmedic/cnnLayerTypes.py to conv3d. Perhaps this change will be sufficient. I will try to make time to check these, but please update us if you try things out and find out the problem.

K

**Comment by csestili** [comment]
Thank you for your responses, Joeri and Konstantinos,

It turned out that the issue was the Theano version (I trained on 0.8.2 and tried to test on 0.9). After installing version 0.8.2 and running testing again, it all worked fine.
