### ISSUE TITLE
Testing on anisotropic data from CT

### ISSUE THREAD

**Issue by ChristianEschen** [Kamnitsask/deepmedic#47]
I am having trouble training my data using the deepMedic model.

I train CT images of size 512x512 and varying number of slices.
The images are resampled to same voxel dimension lets say [0.7,0.7,2]. Next the images are resampled to 250x250x100

Training works fine. However, I  receive an error when I try to test the model. It looks like the metric function evalutes the cost for an input size of 240x240x155.
I there something hardcoded to 240x240x155 or do I miss something?

The error I receive is the following:

+++++++++++++++++++++ Reporting Segmentation Metrics for the subject #0 ++++++++++++++++++++++++++
Traceback (most recent call last):
  File "./deepMedicRun", line 106, in <module>
    deepMedicTest.deepMedicTestMain(absPathToTestConf, absPathToCnnModelGivenInCmdLine)
  File "/home/s123656/deepmedic/deepmedic/frontEndModules/deepMedicTest.py", line 303, in deepMedicTestMain
    performInferenceForTestingOnWholeVolumes(*testSessionParameters.getTupleForCnnTesting())
  File "/home/s123656/deepmedic/deepmedic/trainValidateTestVisualiseParallel.py", line 1805, in performInferenceForTestingOnWholeVolumes
    predictedLabelImageConvolvedWithBrainMask = booleanPredictedLabelImage*multiplyWithBrainMaskOr1
ValueError: operands could not be broadcast together with shapes (250,250,100) (240,240,155)

**Comment by ChristianEschen** [comment]
The issue was related to fact that I had not changed the content of testRoiMasks.cfg.
