### ISSUE TITLE
training error IndexError: index -

### ISSUE THREAD

**Issue by ChristianEschen** [Kamnitsask/deepmedic#49]
Hi 

During training I receive thefollowing error message:
Any clues what is going wrong?

Loading Training data for subepoch #0 on shared variable...
TIMING: Loading sharedVariables for Training in epoch|subepoch=0|0 took time: 0.01057(s)
PARALLEL: Before Training in subepoch #0, submitting the parallel job for extracting Segments for the next Validation.
-T-T-T-T-T- Now Training for this subepoch... This may take a few minutes... -T-T-T-T-T-
Trained on 0/98 of the batches for this subepoch...
Trained on 19/98 of the batches for this subepoch...
Traceback (most recent call last):
  File "./deepMedicRun", line 99, in <module>
    deepMedicTrain.deepMedicTrainMain(absPathToTrainConf, absPathToCnnModelGivenInCmdLine, cnnInstanceLoaded, filenameAndPathWhereNewlyCreatedModelWasSaved)
  File "/nobackup/s123656/notebooks/deepmedic/deepmedic/frontEndModules/deepMedicTrain.py", line 441, in deepMedicTrainMain
    do_training(*trainSessionParameters.getTupleForCnnTraining())
  File "/nobackup/s123656/notebooks/deepmedic/deepmedic/trainValidateTestVisualiseParallel.py", line 1304, in do_training
    trainingAccuracyMonitorForEpoch)
  File "/nobackup/s123656/notebooks/deepmedic/deepmedic/trainValidateTestVisualiseParallel.py", line 886, in doTrainOrValidationOnBatchesAndReturnMeanAccuraciesOfSubepoch
    listWithCostMeanErrorAndRpRnTpTnForEachClassFromTraining = cnn3dInstance.cnnTrainModel(batch_i, vectorWithWeightsOfTheClassesForCostFunctionOfTraining)
  File "/home/s123656/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py", line 898, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/home/s123656/anaconda2/lib/python2.7/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/s123656/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
  File "/home/s123656/anaconda2/lib/python2.7/site-packages/theano/gof/op.py", line 872, in rval
    r = p(n, [x[0] for x in i], o)
  File "/home/s123656/anaconda2/lib/python2.7/site-packages/theano/tensor/subtensor.py", line 2173, in perform
    out[0] = inputs[0].__getitem__(inputs[1:])
IndexError: index -2147483648 is out of bounds for axis 1 with size 2
Apply node that caused the error: AdvancedSubtensor(HostFromGpu.0, TensorConstant{[[[[0]]]

..
 [[[9]]]]}, Elemwise{Cast{int32}}.0, TensorConstant{[[[[0]]

 ..
  [[8]]]]}, TensorConstant{[[[[0]
   ..
   [8]]]]}, TensorConstant{[[[[0 1 2 .. 6 7 8]]]]})
Toposort index: 1931
Inputs types: [TensorType(float32, 5D), TensorType(int64, (False, True, True, True)), TensorType(int32, 4D), TensorType(int64, (True, False, True, True)), TensorType(int64, (True, True, False, True)), TensorType(int64, (True, True, True, False))]
Inputs shapes: [(10, 2, 9, 9, 9), (10, 1, 1, 1), (10, 9, 9, 9), (1, 9, 1, 1), (1, 1, 9, 1), (1, 1, 1, 9)]
Inputs strides: [(5832, 2916, 324, 36, 4), (8, 8, 8, 8), (2916, 324, 36, 4), (72, 8, 8, 8), (72, 72, 8, 8), (72, 72, 72, 8)]
Inputs values: ['not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown']
Outputs clients: [[Sum{acc_dtype=float64}(AdvancedSubtensor.0), Shape_i{3}(AdvancedSubtensor.0), Shape_i{2}(AdvancedSubtensor.0), Shape_i{1}(AdvancedSubtensor.0), Shape_i{0}(AdvancedSubtensor.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "./deepMedicRun", line 92, in <module>
    (cnnInstanceLoaded, filenameAndPathWhereNewlyCreatedModelWasSaved) = deepMedicNewModel.deepMedicNewModelMain(absPathToModelConf)
  File "/nobackup/s123656/notebooks/deepmedic/deepmedic/frontEndModules/deepMedicNewModel.py", line 200, in deepMedicNewModelMain
    cnn3dInstance.compileTrainFunction(*createModelSessionParameters.getTupleForCompilationOfTrainFunc())
  File "/nobackup/s123656/notebooks/deepmedic/deepmedic/cnn3d.py", line 752, in compileTrainFunction
    costFromLastLayer = self.finalLayer.negativeLogLikelihood(y, weightPerClass)
  File "/nobackup/s123656/notebooks/deepmedic/deepmedic/cnnLayerTypes.py", line 692, in negativeLogLikelihood
    return -T.mean( weighted_log_p_y_given_x_train[ indexDim0, y, indexDim2, indexDim3, indexDim4] )

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

**Comment by Kamnitsask** [comment]
Hi,

The fact that it ran for a while tells me that the network is compiled fine. As the last lines point out, the problem seems to come from the calculation of the "negativeLogLikelihood".

Since it's a runtime error that did not occur immediately (it got trained for 20 mini batches), I would advice you to check that your data is fine. Specifically, make sure that no subject's Ground-Truth labels have a value smaller than 0 (eg -1) or greater than the (numberOfClasses-1) you have defined in the modelConfig (note that numberOfClasses includes background). Such an inconsistency would explain the calculation of negativeLogLikelihood crashing.

Kostas

**Comment by ChristianEschen** [comment]
the issue was related to NaN's in the GT's
