### ISSUE TITLE
Getting multiple "ImportError: No module named ..." in early stages of training.

### ISSUE THREAD

**Issue by Kaido0** [Kamnitsask/deepmedic#52]
At first,everything going well,but suddenly something wrong happened.
```
VALIDATION: Epoch #0, Subepoch #0, Class-4:	 mean Dice:       	0.0406
TIMING: Validating on the batches of this subepoch #0 took time: 0.539364(s)
UPDATE: In this last epoch (cnnTrained) #0 the CNN achieved a new highest mean validation accuracy of: 0.0582
An error has occured during the module import
Traceback (most recent call last):
  File "/home/kaido/anaconda2/lib/python2.7/site-packages/ppworker.py", line 55, in preprocess
    globals()[module.split('.')[0]] = __import__(module)
ImportError: No module named numpy as np
An error has occured during the module import
Traceback (most recent call last):
  File "/home/kaido/anaconda2/lib/python2.7/site-packages/ppworker.py", line 55, in preprocess
    globals()[module.split('.')[0]] = __import__(module)
ImportError: No module named nibabel as nib
An error has occured during the module import
Traceback (most recent call last):
  File "/home/kaido/anaconda2/lib/python2.7/site-packages/ppworker.py", line 55, in preprocess
    globals()[module.split('.')[0]] = __import__(module)
ImportError: No module named from deepmedic.genericHelpers import *
An error has occured during the module import
Traceback (most recent call last):
  File "/home/kaido/anaconda2/lib/python2.7/site-packages/ppworker.py", line 55, in preprocess
    globals()[module.split('.')[0]] = __import__(module)
ImportError: No module named from scipy.ndimage.filters import gaussian_filter
:=:=:=:=:=:=:=:=: Starting to extract Segments from the images for next Training... :=:=:=:=:=:=:=:=:
Out of [2] subjects given for [Training], it was specified to extract Segments from maximum [50] per subepoch.
Shuffled indices of subjects that were randomly chosen: [1, 0]
An error has occured during the function execution
Traceback (most recent call last):
  File "/home/kaido/anaconda2/lib/python2.7/site-packages/ppworker.py", line 97, in run
    __result = __f(*__args)
  File "<string>", line 62, in getTheArraysOfImageChannelsAndLesionsToLoadToGpuForSubepoch
  File "<string>", line 6, in getNumberOfSegmentsToExtractPerCategoryFromEachSubject
NameError: global name 'np' is not defined
Traceback (most recent call last):
  File "./deepMedicRun", line 99, in <module>
    deepMedicTrain.deepMedicTrainMain(absPathToTrainConf, absPathToCnnModelGivenInCmdLine, cnnInstanceLoaded, filenameAndPathWhereNewlyCreatedModelWasSaved)
  File "/home/kaido/workspace/deepmedic/deepmedic/frontEndModules/deepMedicTrain.py", line 441, in deepMedicTrainMain
    do_training(*trainSessionParameters.getTupleForCnnTraining())
  File "/home/kaido/workspace/deepmedic/deepmedic/trainValidateTestVisualiseParallel.py", line 1238, in do_training
    subsampledImagePartsChannelsToLoadOnGpuForSubepochTraining] = parallelJobToGetDataForNextTraining() #fromParallelProcessing that had started from last loop when it was submitted.
TypeError: 'NoneType' object is not iterable
```

**Comment by Kaido0** [comment]
WOW~I know,I use pp-1.5.6,It doesn't work,later I try  pp-1.6.5,it is true

**Comment by Kamnitsask** [comment]
Hey Kaido,

Thanks for the feedback. Perhaps other users will find this useful. Thanks a lot.

K
