### ISSUE TITLE
Error while running the sample training

### ISSUE THREAD

**Issue by NaglisRam** [Kamnitsask/deepmedic#57]
Hi, thank you so much for the code! I experience an error while trying to run on the included data:

TIMING: Validating on the batches of this subepoch #0 took time: 14.546188(s)
UPDATE: In this last epoch (cnnTrained) #0 the CNN achieved a new highest mean validation accuracy of: 0.0945512820513
An error has occured during the module import
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pp-1.6.4-py2.7.egg/ppworker.py", line 49, in preprocess
    exec module
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/nibabel-2.1.0-py2.7.egg/nibabel/__init__.py", line 38, in <module>
    from . import analyze as ana
  File "/usr/local/lib/python2.7/dist-packages/nibabel-2.1.0-py2.7.egg/nibabel/analyze.py", line 93, in <module>
    from .spatialimages import (HeaderDataError, HeaderTypeError,
  File "/usr/local/lib/python2.7/dist-packages/nibabel-2.1.0-py2.7.egg/nibabel/spatialimages.py", line 140, in <module>
    from .viewers import OrthoSlicer3D
  File "/usr/local/lib/python2.7/dist-packages/nibabel-2.1.0-py2.7.egg/nibabel/viewers.py", line 12, in <module>
    from .optpkg import optional_package
  File "/usr/local/lib/python2.7/dist-packages/nibabel-2.1.0-py2.7.egg/nibabel/optpkg.py", line 7, in <module>
    import nose
  File "/usr/lib/python2.7/dist-packages/nose/__init__.py", line 1, in <module>
    from nose.core import collector, main, run, run_exit, runmodule
  File "/usr/lib/python2.7/dist-packages/nose/core.py", line 11, in <module>
    from nose.config import Config, all_config_files
  File "/usr/lib/python2.7/dist-packages/nose/config.py", line 9, in <module>
    from nose.plugins.manager import NoPlugins
  File "/usr/lib/python2.7/dist-packages/nose/plugins/__init__.py", line 185, in <module>
    from nose.plugins.manager import *  
File "/usr/lib/python2.7/dist-packages/nose/plugins/manager.py", line 418, in <module>
    import pkg_resources
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/usr/local/lib/python2.7/dist-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)
An error has occured during the module import
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pp-1.6.4-py2.7.egg/ppworker.py", line 49, in preprocess
    exec module
  File "<string>", line 1, in <module>
  File "deepmedic/genericHelpers.py", line 13, in <module>
    import nibabel as nib
  File "/usr/local/lib/python2.7/dist-packages/nibabel-2.1.0-py2.7.egg/nibabel/__init__.py", line 38, in <module>
    from . import analyze as ana
  File "/usr/local/lib/python2.7/dist-packages/nibabel-2.1.0-py2.7.egg/nibabel/analyze.py", line 93, in <module>
    from .spatialimages import (HeaderDataError, HeaderTypeError,
  File "/usr/local/lib/python2.7/dist-packages/nibabel-2.1.0-py2.7.egg/nibabel/spatialimages.py", line 140, in <module>
    from .viewers import OrthoSlicer3D
  File "/usr/local/lib/python2.7/dist-packages/nibabel-2.1.0-py2.7.egg/nibabel/viewers.py", line 12, in <module>
    from .optpkg import optional_package
  File "/usr/local/lib/python2.7/dist-packages/nibabel-2.1.0-py2.7.egg/nibabel/optpkg.py", line 7, in <module>
    import nose
  File "/usr/lib/python2.7/dist-packages/nose/__init__.py", line 1, in <module>
    from nose.core import collector, main, run, run_exit, runmodule
  File "/usr/lib/python2.7/dist-packages/nose/core.py", line 11, in <module>
    from nose.config import Config, all_config_files
  File "/usr/lib/python2.7/dist-packages/nose/config.py", line 9, in <module>
    from nose.plugins.manager import NoPlugins
  File "/usr/lib/python2.7/dist-packages/nose/plugins/__init__.py", line 185, in <module>
    from nose.plugins.manager import *
  File "/usr/lib/python2.7/dist-packages/nose/plugins/manager.py", line 418, in <module>
    import pkg_resources
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/usr/local/lib/python2.7/dist-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)
An error has occured during the module import
An error has occured during the module import
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pp-1.6.4-py2.7.egg/ppworker.py", line 49, in preprocess
    exec module
  File "<string>", line 1, in <module>
  File "deepmedic/cnnHelpers.py", line 9, in <module>
    from genericHelpers import *
  File "deepmedic/genericHelpers.py", line 13, in <module>
    import nibabel as nib
  File "/usr/local/lib/python2.7/dist-packages/nibabel-2.1.0-py2.7.egg/nibabel/__init__.py", line 38, in <module>
    from . import analyze as ana
  File "/usr/local/lib/python2.7/dist-packages/nibabel-2.1.0-py2.7.egg/nibabel/analyze.py", line 93, in <module>
    from .spatialimages import (HeaderDataError, HeaderTypeError,
  File "/usr/local/lib/python2.7/dist-packages/nibabel-2.1.0-py2.7.egg/nibabel/spatialimages.py", line 140, in <module>
    from .viewers import OrthoSlicer3D
  File "/usr/local/lib/python2.7/dist-packages/nibabel-2.1.0-py2.7.egg/nibabel/viewers.py", line 12, in <module>
    from .optpkg import optional_package
  File "/usr/local/lib/python2.7/dist-packages/nibabel-2.1.0-py2.7.egg/nibabel/optpkg.py", line 7, in <module>
    import nose
  File "/usr/lib/python2.7/dist-packages/nose/__init__.py", line 1, in <module>
    from nose.core import collector, main, run, run_exit, runmodule
  File "/usr/lib/python2.7/dist-packages/nose/core.py", line 11, in <module>
    from nose.config import Config, all_config_files
  File "/usr/lib/python2.7/dist-packages/nose/config.py", line 9, in <module>
    from nose.plugins.manager import NoPlugins
  File "/usr/lib/python2.7/dist-packages/nose/plugins/__init__.py", line 185, in <module>
    from nose.plugins.manager import *
  File "/usr/lib/python2.7/dist-packages/nose/plugins/manager.py", line 418, in <module>
    import pkg_resources
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/usr/local/lib/python2.7/dist-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)
A fatal error has occured during the function execution
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pp-1.6.4-py2.7.egg/ppworker.py", line 86, in run
    __args = pickle.loads(__sargs)
  File "deepmedic/cnnHelpers.py", line 9, in <module> 
   from genericHelpers import *
  File "deepmedic/genericHelpers.py", line 13, in <module>
    import nibabel as nib
  File "/usr/local/lib/python2.7/dist-packages/nibabel-2.1.0-py2.7.egg/nibabel/__init__.py", line 38, in <module>
    from . import analyze as ana
  File "/usr/local/lib/python2.7/dist-packages/nibabel-2.1.0-py2.7.egg/nibabel/analyze.py", line 93, in <module>
    from .spatialimages import (HeaderDataError, HeaderTypeError,
  File "/usr/local/lib/python2.7/dist-packages/nibabel-2.1.0-py2.7.egg/nibabel/spatialimages.py", line 140, in <module>
    from .viewers import OrthoSlicer3D
  File "/usr/local/lib/python2.7/dist-packages/nibabel-2.1.0-py2.7.egg/nibabel/viewers.py", line 12, in <module>
    from .optpkg import optional_package
  File "/usr/local/lib/python2.7/dist-packages/nibabel-2.1.0-py2.7.egg/nibabel/optpkg.py", line 7, in <module>
    import nose
  File "/usr/lib/python2.7/dist-packages/nose/__init__.py", line 1, in <module>
    from nose.core import collector, main, run, run_exit, runmodule
  File "/usr/lib/python2.7/dist-packages/nose/core.py", line 11, in <module>
    from nose.config import Config, all_config_files
  File "/usr/lib/python2.7/dist-packages/nose/config.py", line 9, in <module>
    from nose.plugins.manager import NoPlugins
  File "/usr/lib/python2.7/dist-packages/nose/plugins/__init__.py", line 185, in <module>
    from nose.plugins.manager import *
  File "/usr/lib/python2.7/dist-packages/nose/plugins/manager.py", line 418, in <module>
    import pkg_resources
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/usr/local/lib/python2.7/dist-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)
Traceback (most recent call last):
  File "deepMedicRun", line 134, in <module>
    deepMedicTrain.deepMedicTrainMain(absPathToTrainConf, absPathToCnnModelGivenInCmdLine, cnnInstanceLoaded, filenameAndPathWhereNewlyCre
atedModelWasSaved, args.reset_optimizer)
  File "/home/ubuntu/pynb/Naglis/deepmedic-master/deepmedic/frontEndModules/deepMedicTrain.py", line 496, in deepMedicTrainMain
    do_training(*trainSessionParameters.getTupleForCnnTraining())
  File "/home/ubuntu/pynb/Naglis/deepmedic-master/deepmedic/trainValidateTestVisualiseParallel.py", line 1203, in do_training
    labelsForCentralOfSegmentsForSubepTrain] = parallelJobToGetDataForNextTraining() #fromParallelProcessing that had started from last lo
op when it was submitted.
TypeError: 'NoneType' object is not iterable

**Comment by Kamnitsask** [comment]
Hi,

An error when running on the given data and example configs probably indicates that there is some incompatibility with your libraries.

If I understand correctly, this error occured right after the first round of "validation" in the first subepoch, before the first round of training?

Since it ran for a while (first validation cycle was done I believe), it seems that Theano is fine, and so is nibabel (the package for save/load).

I believe you have an issue with pp (parallel python, http://www.parallelpython.com/content/view/18/32/). Check what version you are using.  I remember another user's issue when using an older version. Get 1.6.5 from the link above.

Kostas

**Comment by Kamnitsask** [comment]
Closing this for now as there was no update.
