### ISSUE TITLE
mean cost:      	nan

### ISSUE THREAD

**Issue by 94mia** [Kamnitsask/deepmedic#76]
HI,
i have been trying training 3dcnn model using my own data, but i got the " mean cost :nan " during the whole training session.
i use the default configure file for training, 	is it something wrong with my pre-processing .
![default](https://user-images.githubusercontent.com/24834965/27625409-0f66e944-5c17-11e7-834c-35b6883a0660.png)

**Comment by 94mia** [comment]
once i normalize the data the costs appear to be finite but then suddenly go to NaN after a few iterations. Normalization can only get me so far. If learning rate is too large, each iteration will overshoot in the direction towards the minimum and would thus make the cost at each iteration oscillate or even diverge which is what is appearing to be happening. is that right? and how can i solve this problem?

thanks!

**Comment by 94mia** [comment]
log_p_y_given_x_train = T.log(self.p_y_given_x_train + addTinyProbMatrix)
#added a tiny so that it does not go to zero and I have problems with nan again...


 i have been trying to solve this problem a long time with gradient clipping, reducing learning rate , etc, but making no difference. i am very confused now.

**Comment by 94mia** [comment]
![default](https://user-images.githubusercontent.com/24834965/27776525-e9c59382-5fdd-11e7-9c4f-c067e0f936b8.png)

**Comment by Kamnitsask** [comment]
Hi,

Sorry for this trouble and the late reply. Was abroad and couldn't follow issues.

Did you find the cause of this?

**Comment by 94mia** [comment]
I used the NanGuardMode and the nan was dectected.
 I added the following two lines of code:
theano.config.nvcc.fastmath='False'
theano.config.optimizer='None'

the error message:

Traceback (most recent call last):
  File "/home/mia/mypython/deepmedic-test/deepmedic-master/deepMedicRun", line 137, in <module>
    deepMedicTrain.deepMedicTrainMain(absPathToTrainConf, absPathToCnnModelGivenInCmdLine, cnnInstanceLoaded, filenameAndPathWhereNewlyCreatedModelWasSaved,args.reset_optimizer)#args.reset_optimizer
  File "/home/mia/mypython/deepmedic-test/deepmedic-master/deepmedic/frontEndModules/deepMedicTrain.py", line 496, in deepMedicTrainMain
    do_training(*trainSessionParameters.getTupleForCnnTraining())
  File "/home/mia/mypython/deepmedic-test/deepmedic-master/deepmedic/trainValidateTestVisualiseParallel.py", line 1286, in do_training
    trainingAccuracyMonitorForEpoch)
  File "/home/mia/mypython/deepmedic-test/deepmedic-master/deepmedic/trainValidateTestVisualiseParallel.py", line 885, in doTrainOrValidationOnBatchesAndReturnMeanAccuraciesOfSubepoch
    listWithCostMeanErrorAndRpRnTpTnForEachClassFromTraining = cnn3dInstance.cnnTrainModel(batch_i, vectorWithWeightsOfTheClassesForCostFunctionOfTraining)
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.9.0-py2.7.egg/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.9.0-py2.7.egg/theano/gof/vm.py", line 417, in __call__
    self.callback_input(k, self.storage_map[k][0])
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.9.0-py2.7.egg/theano/compile/nanguardmode.py", line 348, in nan_check_input
    do_check_on(value, None, var=var)
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.9.0-py2.7.egg/theano/compile/nanguardmode.py", line 296, in do_check_on
    if contains_nan(value, nd, var):
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.9.0-py2.7.egg/theano/compile/nanguardmode.py", line 108, in contains_nan
    if not _is_numeric_value(arr, var):
  File "/usr/local/lib/python2.7/dist-packages/Theano-0.9.0-py2.7.egg/theano/compile/nanguardmode.py", line 52, in _is_numeric_value
    elif arr.size == 0:
AttributeError: 'int' object has no attribute 'size'

I was supposed to solve it but it was wrong now
________________________________
发件人: Konstantinos Kamnitsas [notifications@github.com]
发送时间: 2017年7月3日 17:30
收件人: Kamnitsask/deepmedic
Cc: 张丽园; State change
主题: Re: [Kamnitsask/deepmedic] mean cost: nan (#76)


Hi,

Sorry for this trouble and the late reply. Was abroad and couldn't follow issues.

Did you find the cause of this?

―
