### ISSUE TITLE
Getting error when using gpu to train tinyCNN

### ISSUE THREAD

**Issue by pykao** [Kamnitsask/deepmedic#91]
./deepMedicRun -dev cuda -train examples/configFiles/tinyCnn/train/trainConfigWithValidation.cfg -model examples/output/cnnModels/tinyCnn.initial.2017-11-14.16.48.21.764469.save 

It gave me the error:
First:
Can not use cuDNN on context None: cannot compile with cuDNN. We got this error:
/tmp/try_flags_GrN6H5.c:4:19: fatal error: cudnn.h: No such file or directory
compilation terminated.

ERROR (theano.gpuarray): Could not initialize pygpu, support disabled
Traceback (most recent call last):
  File "/home/pkao/miniconda2/envs/condaEnv_dm/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 220, in <module>
    use(config.device)
  File "/home/pkao/miniconda2/envs/condaEnv_dm/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 207, in use
    init_dev(device, preallocate=preallocate)
  File "/home/pkao/miniconda2/envs/condaEnv_dm/lib/python2.7/site-packages/theano/gpuarray/__init__.py", line 133, in init_dev
    context.free_gmem / MB))
RuntimeError: Trying to preallocate 3832 MB of GPU memory while only 3527 MB are available.

Second:

=======================================================
2017-11-14 17:06:59.400820 >> ============== Training the CNN model =================
2017-11-14 17:06:59.400837 >> =======================================================
2017-11-14 17:06:59.407113 >> CONFIG: Theano is using the [CPU].
2017-11-14 17:06:59.407165 >> ERROR:	 The THEANO_FLAGS, as set either in the environment or via the deepMedicRun script, they enforced the use of GPU.
	 However an internal check showed that Theano has not managed to start on the GPU.
	 Please check for any error messages thrown above by Theano (eg when loading or compiling the model) for indications about the problem.
	 Given THEANO_FLAGS= ,on_unused_input=warn,mode=FAST_RUN,device=cuda,floatX=float32,force_device=True,dnn.enabled=auto,gpuarray.preallocate=1,openmp=True

**Comment by pykao** [comment]
I solved the problem by using

THEANO_FLAGS='gpuarray.preallocate=0.7' python ./deepMedicRun -train ...rest of arguments...

**Comment by Kamnitsask** [comment]
Yes, sorry, by default I was preallocating all (95%) the GPU memory by default, which for small GPUs it may break cause there may not be enough memory left for the monitor.

Default behaviour has now been changed, preallocation won't happen. If you wish preallocation, pass the above theano flag in the command line, or edit its default value in the file ./deepMedicRun -> line 125.
